// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.
// SPDX-License-Identifier: Apache-2.0
//
// The boundary between the engine and the TypeScript half, in Rust.
// Regenerate after any change to the schema; CI fails on a difference.

#![allow(dead_code)]

use core::mem::offset_of;

pub const ABI_MAJOR: u32 = 0;
pub const ABI_HASH: u32 = 0x175e3db4;
pub const ABI_VERSION: u32 = 0x005e3db4;

pub const COMMAND_PAYLOAD_OFFSET: usize = 8;
pub const COMMAND_PAYLOAD_SIZE: usize = 24;

#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum CommandKind {
    Play = 1,
    Stop = 2,
    SetTempo = 3,
}

impl CommandKind {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(Self::Play),
            2 => Some(Self::Stop),
            3 => Some(Self::SetTempo),
            _ => None,
        }
    }

    pub fn code(self) -> u32 {
        self as u32
    }
}

#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum EngineError {
    Ok = 0,
    UnknownCommandKind = 1,
    BadFrameCount = 2,
}

impl EngineError {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            0 => Some(Self::Ok),
            1 => Some(Self::UnknownCommandKind),
            2 => Some(Self::BadFrameCount),
            _ => None,
        }
    }

    pub fn code(self) -> u32 {
        self as u32
    }
}

#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TransportState {
    Stopped = 0,
    Playing = 1,
}

impl TransportState {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            0 => Some(Self::Stopped),
            1 => Some(Self::Playing),
            _ => None,
        }
    }

    pub fn code(self) -> u32 {
        self as u32
    }
}

#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct CommandSlot {
    pub kind: u32,
    pub frame_offset: u32,
    pub payload: [u8; 24],
}

impl CommandSlot {
    pub const KIND_OFFSET: usize = 0;
    pub const FRAME_OFFSET_OFFSET: usize = 4;
    pub const PAYLOAD_OFFSET: usize = 8;
    pub const SIZE: usize = 32;
}

const _: () = assert!(size_of::<CommandSlot>() == 32);
const _: () = assert!(offset_of!(CommandSlot, kind) == 0);
const _: () = assert!(offset_of!(CommandSlot, frame_offset) == 4);
const _: () = assert!(offset_of!(CommandSlot, payload) == 8);

#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct MeterBlock {
    pub block_counter: i32,
    pub position_frames: i32,
    pub peak_micro: i32,
    pub transport_state: i32,
}

impl MeterBlock {
    pub const BLOCK_COUNTER_OFFSET: usize = 0;
    pub const POSITION_FRAMES_OFFSET: usize = 4;
    pub const PEAK_MICRO_OFFSET: usize = 8;
    pub const TRANSPORT_STATE_OFFSET: usize = 12;
    pub const SIZE: usize = 16;
}

const _: () = assert!(size_of::<MeterBlock>() == 16);
const _: () = assert!(offset_of!(MeterBlock, block_counter) == 0);
const _: () = assert!(offset_of!(MeterBlock, position_frames) == 4);
const _: () = assert!(offset_of!(MeterBlock, peak_micro) == 8);
const _: () = assert!(offset_of!(MeterBlock, transport_state) == 12);

/// Command `play`, code 1, read from and written to a slot's payload.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Play {
    pub from_frame: u32,
}

impl Play {
    pub const KIND: CommandKind = CommandKind::Play;
    pub const FROM_FRAME_OFFSET: usize = 0;

    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {
        Self {
            from_frame: u32::from_le_bytes([payload[0], payload[1], payload[2], payload[3]]),
        }
    }

    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {
        *payload = [0u8; COMMAND_PAYLOAD_SIZE];
        let bytes = self.from_frame.to_le_bytes();
        payload[0] = bytes[0];
        payload[1] = bytes[1];
        payload[2] = bytes[2];
        payload[3] = bytes[3];
    }
}

const _: () = assert!(size_of::<Play>() <= 24);

/// Command `set_tempo`, code 3, read from and written to a slot's payload.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct SetTempo {
    pub micro_bpm: u32,
}

impl SetTempo {
    pub const KIND: CommandKind = CommandKind::SetTempo;
    pub const MICRO_BPM_OFFSET: usize = 0;

    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {
        Self {
            micro_bpm: u32::from_le_bytes([payload[0], payload[1], payload[2], payload[3]]),
        }
    }

    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {
        *payload = [0u8; COMMAND_PAYLOAD_SIZE];
        let bytes = self.micro_bpm.to_le_bytes();
        payload[0] = bytes[0];
        payload[1] = bytes[1];
        payload[2] = bytes[2];
        payload[3] = bytes[3];
    }
}

const _: () = assert!(size_of::<SetTempo>() <= 24);

/// Command `stop`, code 2, read from and written to a slot's payload.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Stop {}

impl Stop {
    pub const KIND: CommandKind = CommandKind::Stop;

    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {
        let _ = payload;
        Self {}
    }

    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {
        *payload = [0u8; COMMAND_PAYLOAD_SIZE];
    }
}

const _: () = assert!(size_of::<Stop>() <= 24);

/// The functions the engine must export (ADR-0015). The wasm host test
/// checks the built module against this list.
pub const EXPORT_FUNCTIONS: [&str; 7] = [
    "abi_version",
    "init",
    "command_staging_ptr",
    "command_staging_capacity",
    "audio_out_ptr",
    "meter_block_ptr",
    "process",
];
