// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.
// SPDX-License-Identifier: Apache-2.0
//
// The boundary between the engine and the TypeScript half, in Rust.
// Regenerate after any change to the schema; CI fails on a difference.

#![allow(dead_code)]

use core::mem::offset_of;

/// The boundary's major version, set by hand in the schema.
pub const ABI_MAJOR: u32 = 0;
/// A hash of the schema, so that editing a field moves the version.
pub const ABI_HASH: u32 = 0x8bc0ff11;
/// The version the engine must report from `abi_version`: the major
/// number in the top byte, the hash of the schema in the rest.
pub const ABI_VERSION: u32 = 0x00c0ff11;

/// Where a slot's payload begins, in bytes from the slot.
pub const COMMAND_PAYLOAD_OFFSET: usize = 8;
/// How many bytes of a slot a command has to itself.
pub const COMMAND_PAYLOAD_SIZE: usize = 24;
/// How many command slots the staging area holds. The glue copies at most this
/// many in a block and leaves the rest in the ring for the next.
pub const COMMAND_STAGING_CAPACITY: usize = 256;
/// The fastest tempo the engine accepts, in micro-BPM: 999 BPM.
pub const MICRO_BPM_MAX: usize = 999000000;
/// The slowest tempo the engine accepts, in micro-BPM: 10 BPM.
pub const MICRO_BPM_MIN: usize = 10000000;

#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum CommandKind {
    Play = 1,
    Stop = 2,
    SetTempo = 3,
}

impl CommandKind {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            1 => Some(Self::Play),
            2 => Some(Self::Stop),
            3 => Some(Self::SetTempo),
            _ => None,
        }
    }

    pub fn code(self) -> u32 {
        self as u32
    }
}

#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum EngineError {
    /// The call did what it was asked.
    Ok = 0,
    /// A slot carried a kind the engine does not know.
    UnknownCommandKind = 1,
    /// A block of more frames than a plane of `audio_out` holds.
    BadFrameCount = 2,
    /// A sample rate that is not a positive, finite number.
    BadSampleRate = 3,
    /// `process` before a successful `init`.
    NotInitialised = 4,
    /// More commands than the staging area holds.
    TooManyCommands = 5,
    /// A command of a kind the engine knows, carrying a value it cannot use.
    BadCommandPayload = 6,
    /// A command placed at or beyond the end of the block it arrived with.
    BadFrameOffset = 7,
    /// A command placed before the one ahead of it in the staging area.
    CommandsOutOfOrder = 8,
}

impl EngineError {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            0 => Some(Self::Ok),
            1 => Some(Self::UnknownCommandKind),
            2 => Some(Self::BadFrameCount),
            3 => Some(Self::BadSampleRate),
            4 => Some(Self::NotInitialised),
            5 => Some(Self::TooManyCommands),
            6 => Some(Self::BadCommandPayload),
            7 => Some(Self::BadFrameOffset),
            8 => Some(Self::CommandsOutOfOrder),
            _ => None,
        }
    }

    pub fn code(self) -> u32 {
        self as u32
    }
}

#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TransportState {
    Stopped = 0,
    Playing = 1,
}

impl TransportState {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            0 => Some(Self::Stopped),
            1 => Some(Self::Playing),
            _ => None,
        }
    }

    pub fn code(self) -> u32 {
        self as u32
    }
}

/// The block the engine renders into, in its own unshared memory, one run of
/// samples per channel. A block fills the first `frames` samples of each plane and
/// leaves the rest of it as the previous block left it.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct AudioOut {
    /// The left channel, as long as the largest block the engine accepts.
    pub left: [f32; 1024],
    /// The right channel, as long as the largest block the engine accepts.
    pub right: [f32; 1024],
}

impl AudioOut {
    /// Byte offset of `left` inside `audio_out`.
    pub const LEFT_OFFSET: usize = 0;
    /// Byte offset of `right` inside `audio_out`.
    pub const RIGHT_OFFSET: usize = 4096;
    /// `audio_out` in bytes.
    pub const SIZE: usize = 8192;
}

const _: () = assert!(size_of::<AudioOut>() == 8192);
const _: () = assert!(offset_of!(AudioOut, left) == 0);
const _: () = assert!(offset_of!(AudioOut, right) == 4096);

/// One slot of the command ring, copied into the staging area as it stands. The
/// engine reads the header of every slot; the payload only the slot's own kind
/// knows how to read.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct CommandSlot {
    /// Which command this is, one of the `command_kind` codes.
    pub kind: u32,
    /// Where in the block the command takes effect, in frames from its start. At or
    /// beyond the end of the block it is dropped as `bad_frame_offset`.
    pub frame_offset: u32,
    /// The command's own fields, laid out by its kind, and zero wherever the kind declares nothing.
    pub payload: [u8; 24],
}

impl CommandSlot {
    /// Byte offset of `kind` inside `command_slot`.
    pub const KIND_OFFSET: usize = 0;
    /// Byte offset of `frame_offset` inside `command_slot`.
    pub const FRAME_OFFSET_OFFSET: usize = 4;
    /// Byte offset of `payload` inside `command_slot`.
    pub const PAYLOAD_OFFSET: usize = 8;
    /// `command_slot` in bytes.
    pub const SIZE: usize = 32;
}

const _: () = assert!(size_of::<CommandSlot>() == 32);
const _: () = assert!(offset_of!(CommandSlot, kind) == 0);
const _: () = assert!(offset_of!(CommandSlot, frame_offset) == 4);
const _: () = assert!(offset_of!(CommandSlot, payload) == 8);

/// What the engine has to say about the block it has just rendered, in its own
/// unshared memory. The glue reads it once `process` has returned and publishes
/// what the interface needs into `meter_block`.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct EngineReport {
    /// The playhead at the end of this block, in frames from the start of the timeline.
    pub position_frames: i32,
    /// The largest sample of this block, over both channels, as an amplitude times a million: 1.0 is 1000000.
    pub peak_amp_micro: i32,
    /// The transport as this block left it, one of the `transport_state` codes.
    pub transport_state: i32,
    /// How many of this block's commands the engine dropped, whatever the reason. Per block, not cumulative.
    pub dropped_commands: u32,
}

impl EngineReport {
    /// Byte offset of `position_frames` inside `engine_report`.
    pub const POSITION_FRAMES_OFFSET: usize = 0;
    /// Byte offset of `peak_amp_micro` inside `engine_report`.
    pub const PEAK_AMP_MICRO_OFFSET: usize = 4;
    /// Byte offset of `transport_state` inside `engine_report`.
    pub const TRANSPORT_STATE_OFFSET: usize = 8;
    /// Byte offset of `dropped_commands` inside `engine_report`.
    pub const DROPPED_COMMANDS_OFFSET: usize = 12;
    /// `engine_report` in bytes.
    pub const SIZE: usize = 16;
}

const _: () = assert!(size_of::<EngineReport>() == 16);
const _: () = assert!(offset_of!(EngineReport, position_frames) == 0);
const _: () = assert!(offset_of!(EngineReport, peak_amp_micro) == 4);
const _: () = assert!(offset_of!(EngineReport, transport_state) == 8);
const _: () = assert!(offset_of!(EngineReport, dropped_commands) == 12);

/// What the interface reads, in the shared buffer, published by the glue.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct MeterBlock {
    /// How many blocks the glue has published. The engine does not count blocks.
    pub block_counter: i32,
    /// The playhead as of the published block, in frames from the start of the timeline.
    pub position_frames: i32,
    /// The meter to draw, as an amplitude times a million. The glue holds and decays
    /// the engine's per-block peak into this; what the interface adds is the curve,
    /// not a second decay.
    pub peak_amp_micro: i32,
    /// The transport as of the published block, one of the `transport_state` codes.
    pub transport_state: i32,
}

impl MeterBlock {
    /// Byte offset of `block_counter` inside `meter_block`.
    pub const BLOCK_COUNTER_OFFSET: usize = 0;
    /// Byte offset of `position_frames` inside `meter_block`.
    pub const POSITION_FRAMES_OFFSET: usize = 4;
    /// Byte offset of `peak_amp_micro` inside `meter_block`.
    pub const PEAK_AMP_MICRO_OFFSET: usize = 8;
    /// Byte offset of `transport_state` inside `meter_block`.
    pub const TRANSPORT_STATE_OFFSET: usize = 12;
    /// `meter_block` in bytes.
    pub const SIZE: usize = 16;
}

const _: () = assert!(size_of::<MeterBlock>() == 16);
const _: () = assert!(offset_of!(MeterBlock, block_counter) == 0);
const _: () = assert!(offset_of!(MeterBlock, position_frames) == 4);
const _: () = assert!(offset_of!(MeterBlock, peak_amp_micro) == 8);
const _: () = assert!(offset_of!(MeterBlock, transport_state) == 12);

/// Start the transport.
/// Command `play`, code 1, read from and written to a slot's payload.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Play {
    /// Where to start, in frames from the start of the timeline.
    pub from_frame: u32,
}

impl Play {
    /// The code a slot carries to name this command.
    pub const KIND: CommandKind = CommandKind::Play;
    /// Byte offset of `from_frame` inside the slot's payload.
    pub const FROM_FRAME_OFFSET: usize = 0;

    /// Reads `play` out of a slot's payload.
    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {
        Self {
            from_frame: u32::from_le_bytes([payload[0], payload[1], payload[2], payload[3]]),
        }
    }

    /// Writes `play` into a slot's payload, clearing every byte the
    /// command does not use: a slot is reused.
    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {
        *payload = [0u8; COMMAND_PAYLOAD_SIZE];
        let bytes = self.from_frame.to_le_bytes();
        payload[0] = bytes[0];
        payload[1] = bytes[1];
        payload[2] = bytes[2];
        payload[3] = bytes[3];
    }
}

const _: () = assert!(size_of::<Play>() <= 24);

/// Set the tempo from this point in the block onwards.
/// Command `set_tempo`, code 3, read from and written to a slot's payload.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct SetTempo {
    /// Beats per minute times a million: 120 BPM is 120000000. Outside `micro_bpm_min`
    /// to `micro_bpm_max` the command is dropped as `bad_command_payload`.
    pub micro_bpm: u32,
}

impl SetTempo {
    /// The code a slot carries to name this command.
    pub const KIND: CommandKind = CommandKind::SetTempo;
    /// Byte offset of `micro_bpm` inside the slot's payload.
    pub const MICRO_BPM_OFFSET: usize = 0;

    /// Reads `set_tempo` out of a slot's payload.
    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {
        Self {
            micro_bpm: u32::from_le_bytes([payload[0], payload[1], payload[2], payload[3]]),
        }
    }

    /// Writes `set_tempo` into a slot's payload, clearing every byte the
    /// command does not use: a slot is reused.
    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {
        *payload = [0u8; COMMAND_PAYLOAD_SIZE];
        let bytes = self.micro_bpm.to_le_bytes();
        payload[0] = bytes[0];
        payload[1] = bytes[1];
        payload[2] = bytes[2];
        payload[3] = bytes[3];
    }
}

const _: () = assert!(size_of::<SetTempo>() <= 24);

/// Stop the transport.
/// Command `stop`, code 2, read from and written to a slot's payload.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Stop {}

impl Stop {
    /// The code a slot carries to name this command.
    pub const KIND: CommandKind = CommandKind::Stop;

    /// Reads `stop` out of a slot's payload.
    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {
        let _ = payload;
        Self {}
    }

    /// Writes `stop` into a slot's payload, clearing every byte the
    /// command does not use: a slot is reused.
    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {
        *payload = [0u8; COMMAND_PAYLOAD_SIZE];
    }
}

const _: () = assert!(size_of::<Stop>() <= 24);

/// The functions the engine must export (ADR-0015). The wasm host test
/// checks the built module against this list.
pub const EXPORT_FUNCTIONS: [&str; 6] = [
    "abi_version",
    "init",
    "command_staging_ptr",
    "audio_out_ptr",
    "engine_report_ptr",
    "process",
];
