[package]
name = "escapement-worklet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
escapement-core.workspace = true
escapement-protocol.workspace = true

[lints]
workspace = true
