// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.
// SPDX-License-Identifier: Apache-2.0
//
// The boundary between the engine and the TypeScript half.
// Every multi-byte read and write below passes the little-endian flag.
// Atomic accessors take an Int32Array and a byte offset that must be
// 4-byte aligned; the generator refuses any field where it is not.

export const ABI_MAJOR = 0
export const ABI_HASH = 0x8bc0ff11
export const ABI_VERSION = 0x00c0ff11

/** Where a slot's payload begins, in bytes from the slot. */
export const COMMAND_PAYLOAD_OFFSET = 8
/** How many bytes of a slot a command has to itself. */
export const COMMAND_PAYLOAD_SIZE = 24
/**
 * How many command slots the staging area holds. The glue copies at most this
 * many in a block and leaves the rest in the ring for the next.
 */
export const COMMAND_STAGING_CAPACITY = 256
/** The fastest tempo the engine accepts, in micro-BPM: 999 BPM. */
export const MICRO_BPM_MAX = 999000000
/** The slowest tempo the engine accepts, in micro-BPM: 10 BPM. */
export const MICRO_BPM_MIN = 10000000

export const CommandKind = {
  play: 1,
  stop: 2,
  setTempo: 3,
} as const
export type CommandKindCode = (typeof CommandKind)[keyof typeof CommandKind]

export const EngineError = {
  /** The call did what it was asked. */
  ok: 0,
  /** A slot carried a kind the engine does not know. */
  unknownCommandKind: 1,
  /** A block of more frames than a plane of `audio_out` holds. */
  badFrameCount: 2,
  /** A sample rate that is not a positive, finite number. */
  badSampleRate: 3,
  /** `process` before a successful `init`. */
  notInitialised: 4,
  /** More commands than the staging area holds. */
  tooManyCommands: 5,
  /** A command of a kind the engine knows, carrying a value it cannot use. */
  badCommandPayload: 6,
  /** A command placed at or beyond the end of the block it arrived with. */
  badFrameOffset: 7,
  /** A command placed before the one ahead of it in the staging area. */
  commandsOutOfOrder: 8,
} as const
export type EngineErrorCode = (typeof EngineError)[keyof typeof EngineError]

export const TransportState = {
  stopped: 0,
  playing: 1,
} as const
export type TransportStateCode = (typeof TransportState)[keyof typeof TransportState]

/**
 * The block the engine renders into, in its own unshared memory, one run of
 * samples per channel. A block fills the first `frames` samples of each plane and
 * leaves the rest of it as the previous block left it.
 */
export const AudioOutOffsets = {
  /** The left channel, as long as the largest block the engine accepts. */
  left: 0,
  /** The right channel, as long as the largest block the engine accepts. */
  right: 4096,
} as const
export const AUDIO_OUT_SIZE = 8192

export const AUDIO_OUT_LEFT_LENGTH = 1024

/** A `Float32Array` over `left` of `audio_out`. Cold path: the view is an allocation, so take it once and keep it. `base` must be a multiple of 4. */
export function audioOutLeft(buffer: ArrayBufferLike, base: number): Float32Array {
  return new Float32Array(buffer, base, AUDIO_OUT_LEFT_LENGTH)
}

export const AUDIO_OUT_RIGHT_LENGTH = 1024

/** A `Float32Array` over `right` of `audio_out`. Cold path: the view is an allocation, so take it once and keep it. `base` must be a multiple of 4. */
export function audioOutRight(buffer: ArrayBufferLike, base: number): Float32Array {
  return new Float32Array(buffer, base + 4096, AUDIO_OUT_RIGHT_LENGTH)
}

/**
 * One slot of the command ring, copied into the staging area as it stands. The
 * engine reads the header of every slot; the payload only the slot's own kind
 * knows how to read.
 */
export const CommandSlotOffsets = {
  /** Which command this is, one of the `command_kind` codes. */
  kind: 0,
  /**
   * Where in the block the command takes effect, in frames from its start. At or
   * beyond the end of the block it is dropped as `bad_frame_offset`.
   */
  frameOffset: 4,
  /** The command's own fields, laid out by its kind, and zero wherever the kind declares nothing. */
  payload: 8,
} as const
export const COMMAND_SLOT_SIZE = 32

export function readCommandSlotKind(view: DataView, base: number): number {
  return view.getUint32(base, true)
}

export function writeCommandSlotKind(view: DataView, base: number, value: number): void {
  view.setUint32(base, value, true)
}

export function readCommandSlotFrameOffset(view: DataView, base: number): number {
  return view.getUint32(base + 4, true)
}

export function writeCommandSlotFrameOffset(view: DataView, base: number, value: number): void {
  view.setUint32(base + 4, value, true)
}

export const COMMAND_SLOT_PAYLOAD_LENGTH = 24

/** A `Uint8Array` over `payload` of `command_slot`. Cold path: the view is an allocation, so take it once and keep it. */
export function commandSlotPayload(buffer: ArrayBufferLike, base: number): Uint8Array {
  return new Uint8Array(buffer, base + 8, COMMAND_SLOT_PAYLOAD_LENGTH)
}

/** Cold path: a snapshot of `command_slot`. Allocates one object. */
export function readCommandSlot(view: DataView, base: number) {
  return {
    kind: readCommandSlotKind(view, base),
    frameOffset: readCommandSlotFrameOffset(view, base),
  }
}

/**
 * What the engine has to say about the block it has just rendered, in its own
 * unshared memory. The glue reads it once `process` has returned and publishes
 * what the interface needs into `meter_block`.
 */
export const EngineReportOffsets = {
  /** The playhead at the end of this block, in frames from the start of the timeline. */
  positionFrames: 0,
  /** The largest sample of this block, over both channels, as an amplitude times a million: 1.0 is 1000000. */
  peakAmpMicro: 4,
  /** The transport as this block left it, one of the `transport_state` codes. */
  transportState: 8,
  /** How many of this block's commands the engine dropped, whatever the reason. Per block, not cumulative. */
  droppedCommands: 12,
} as const
export const ENGINE_REPORT_SIZE = 16

export function readEngineReportPositionFrames(view: DataView, base: number): number {
  return view.getInt32(base, true)
}

export function writeEngineReportPositionFrames(view: DataView, base: number, value: number): void {
  view.setInt32(base, value, true)
}

export function readEngineReportPeakAmpMicro(view: DataView, base: number): number {
  return view.getInt32(base + 4, true)
}

export function writeEngineReportPeakAmpMicro(view: DataView, base: number, value: number): void {
  view.setInt32(base + 4, value, true)
}

export function readEngineReportTransportState(view: DataView, base: number): number {
  return view.getInt32(base + 8, true)
}

export function writeEngineReportTransportState(view: DataView, base: number, value: number): void {
  view.setInt32(base + 8, value, true)
}

export function readEngineReportDroppedCommands(view: DataView, base: number): number {
  return view.getUint32(base + 12, true)
}

export function writeEngineReportDroppedCommands(view: DataView, base: number, value: number): void {
  view.setUint32(base + 12, value, true)
}

/** Cold path: a snapshot of `engine_report`. Allocates one object. */
export function readEngineReport(view: DataView, base: number) {
  return {
    positionFrames: readEngineReportPositionFrames(view, base),
    peakAmpMicro: readEngineReportPeakAmpMicro(view, base),
    transportState: readEngineReportTransportState(view, base),
    droppedCommands: readEngineReportDroppedCommands(view, base),
  }
}

/** What the interface reads, in the shared buffer, published by the glue. */
export const MeterBlockOffsets = {
  /** How many blocks the glue has published. The engine does not count blocks. */
  blockCounter: 0,
  /** The playhead as of the published block, in frames from the start of the timeline. */
  positionFrames: 4,
  /**
   * The meter to draw, as an amplitude times a million. The glue holds and decays
   * the engine's per-block peak into this; what the interface adds is the curve,
   * not a second decay.
   */
  peakAmpMicro: 8,
  /** The transport as of the published block, one of the `transport_state` codes. */
  transportState: 12,
} as const
export const METER_BLOCK_SIZE = 16

export function loadMeterBlockBlockCounter(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, base >> 2)
}

export function storeMeterBlockBlockCounter(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, base >> 2, value)
}

export function loadMeterBlockPositionFrames(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 4) >> 2)
}

export function storeMeterBlockPositionFrames(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 4) >> 2, value)
}

export function loadMeterBlockPeakAmpMicro(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 8) >> 2)
}

export function storeMeterBlockPeakAmpMicro(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 8) >> 2, value)
}

export function loadMeterBlockTransportState(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 12) >> 2)
}

export function storeMeterBlockTransportState(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 12) >> 2, value)
}

/** Cold path: a snapshot of `meter_block`. Allocates one object. */
export function readMeterBlock(atoms: Int32Array, base: number) {
  return {
    blockCounter: loadMeterBlockBlockCounter(atoms, base),
    positionFrames: loadMeterBlockPositionFrames(atoms, base),
    peakAmpMicro: loadMeterBlockPeakAmpMicro(atoms, base),
    transportState: loadMeterBlockTransportState(atoms, base),
  }
}

/** Start the transport. */
/**
 * Writes a complete `play` slot (kind 1). Hot path: no allocation.
 * @param fromFrame - Where to start, in frames from the start of the timeline.
 */
export function writePlay(view: DataView, slot: number, frameOffset: number, fromFrame: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 1, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
  view.setUint32(slot + COMMAND_PAYLOAD_OFFSET, fromFrame, true)
}

/** Cold path: allocates an object. Not for use inside process(). */
export function readPlay(view: DataView, slot: number) {
  return {
    fromFrame: view.getUint32(slot + COMMAND_PAYLOAD_OFFSET, true),
  }
}

/** Set the tempo from this point in the block onwards. */
/**
 * Writes a complete `set_tempo` slot (kind 3). Hot path: no allocation.
 * @param microBpm - Beats per minute times a million: 120 BPM is 120000000. Outside `micro_bpm_min`
 *   to `micro_bpm_max` the command is dropped as `bad_command_payload`.
 */
export function writeSetTempo(view: DataView, slot: number, frameOffset: number, microBpm: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 3, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
  view.setUint32(slot + COMMAND_PAYLOAD_OFFSET, microBpm, true)
}

/** Cold path: allocates an object. Not for use inside process(). */
export function readSetTempo(view: DataView, slot: number) {
  return {
    microBpm: view.getUint32(slot + COMMAND_PAYLOAD_OFFSET, true),
  }
}

/** Stop the transport. */
/** Writes a complete `stop` slot (kind 2). Hot path: no allocation. */
export function writeStop(view: DataView, slot: number, frameOffset: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 2, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
}

export interface EngineExports {
  /** The engine's own linear memory, unshared, and never grown after `init` — growing it detaches every view the glue holds (ADR-0015). */
  memory: WebAssembly.Memory
  /** The ABI this module was built against. The glue refuses a module whose version differs from the generated `ABI_VERSION` (ADR-0015). */
  abi_version(): number
  /** Prepares the engine for a sample rate, and returns `ok` or `bad_sample_rate`. Nothing is sized here: the buffers are statics this file measures (ADR-0020). */
  init(sampleRate: number): number
  /** Where the glue copies the slots it drained. Stable for the life of the instance, so the glue takes its view once. */
  command_staging_ptr(): number
  /** Where the engine leaves the block it rendered. Stable for the life of the instance, so the glue takes its views once. */
  audio_out_ptr(): number
  /** Where the engine writes its report. Stable for the life of the instance, so the glue takes its view once. */
  engine_report_ptr(): number
  /**
   * Renders one block. The glue has copied `command_count` slots into the staging
   * area, in non-decreasing `frame_offset`, each of them below `frames`; `frames`
   * is at most as many as a plane of `audio_out` holds.
   *
   * An error is a report, not control flow: a command the engine cannot use is
   * dropped and counted in `engine_report.dropped_commands`, the block is rendered
   * regardless, and what comes back is the first code raised (ADR-0002).
   */
  process(commandCount: number, frames: number): number
}
