// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.
// SPDX-License-Identifier: Apache-2.0
//
// The boundary between the engine and the TypeScript half.
// Every multi-byte read and write below passes the little-endian flag.
// Atomic accessors take an Int32Array and a byte offset that must be
// 4-byte aligned; the generator refuses any field where it is not.

export const ABI_MAJOR = 0
export const ABI_HASH = 0x22b56abb
export const ABI_VERSION = 0x00b56abb

export const COMMAND_PAYLOAD_OFFSET = 8
export const COMMAND_PAYLOAD_SIZE = 24

export const CommandKind = {
  play: 1,
  stop: 2,
  setTempo: 3,
} as const
export type CommandKindCode = (typeof CommandKind)[keyof typeof CommandKind]

export const EngineError = {
  /** The call did what it was asked. */
  ok: 0,
  /** A slot carried a kind the engine does not know. */
  unknownCommandKind: 1,
  /** A block of more frames than a plane of `audio_out` holds. */
  badFrameCount: 2,
  /** A sample rate that is not a positive, finite number. */
  badSampleRate: 3,
  /** `process` before a successful `init`. */
  notInitialised: 4,
  /** More commands than the staging area holds. */
  tooManyCommands: 5,
  /** A command of a kind the engine knows, carrying a value it cannot use. */
  badCommandPayload: 6,
  /** A command placed at or beyond the end of the block it arrived with. */
  badFrameOffset: 7,
  /** A command placed before the one ahead of it in the staging area. */
  commandsOutOfOrder: 8,
} as const
export type EngineErrorCode = (typeof EngineError)[keyof typeof EngineError]

export const TransportState = {
  stopped: 0,
  playing: 1,
} as const
export type TransportStateCode = (typeof TransportState)[keyof typeof TransportState]

/**
 * The block the engine renders into, in its own unshared memory. One run of
 * samples per channel at a fixed offset: Web Audio hands the worklet a
 * Float32Array per channel, and an offset is one number rather than a stride each
 * side works out for itself. A block fills the first `frames` samples of each
 * plane and leaves the rest of it as the previous block left it.
 */
export const AudioOutOffsets = {
  left: 0,
  right: 4096,
} as const
export const AUDIO_OUT_SIZE = 8192

/** The left channel, as long as the largest block the engine accepts. */
export const AUDIO_OUT_LEFT_LENGTH = 1024

/**
 * The left channel, as long as the largest block the engine accepts.
 * A `Float32Array` over `left` of `audio_out`. Cold path: the view is an allocation, so take it once and keep it. `base` must be a multiple of 4.
 */
export function audioOutLeft(buffer: ArrayBufferLike, base: number): Float32Array {
  return new Float32Array(buffer, base, AUDIO_OUT_LEFT_LENGTH)
}

/** The right channel, as long as the largest block the engine accepts. */
export const AUDIO_OUT_RIGHT_LENGTH = 1024

/**
 * The right channel, as long as the largest block the engine accepts.
 * A `Float32Array` over `right` of `audio_out`. Cold path: the view is an allocation, so take it once and keep it. `base` must be a multiple of 4.
 */
export function audioOutRight(buffer: ArrayBufferLike, base: number): Float32Array {
  return new Float32Array(buffer, base + 4096, AUDIO_OUT_RIGHT_LENGTH)
}

export const CommandSlotOffsets = {
  kind: 0,
  frameOffset: 4,
  payload: 8,
} as const
export const COMMAND_SLOT_SIZE = 32

export function readCommandSlotKind(view: DataView, base: number): number {
  return view.getUint32(base, true)
}

export function writeCommandSlotKind(view: DataView, base: number, value: number): void {
  view.setUint32(base, value, true)
}

export function readCommandSlotFrameOffset(view: DataView, base: number): number {
  return view.getUint32(base + 4, true)
}

export function writeCommandSlotFrameOffset(view: DataView, base: number, value: number): void {
  view.setUint32(base + 4, value, true)
}

export const COMMAND_SLOT_PAYLOAD_LENGTH = 24

/** A `Uint8Array` over `payload` of `command_slot`. Cold path: the view is an allocation, so take it once and keep it. */
export function commandSlotPayload(buffer: ArrayBufferLike, base: number): Uint8Array {
  return new Uint8Array(buffer, base + 8, COMMAND_SLOT_PAYLOAD_LENGTH)
}

/** Cold path: a snapshot of `command_slot`. Allocates one object. */
export function readCommandSlot(view: DataView, base: number) {
  return {
    kind: readCommandSlotKind(view, base),
    frameOffset: readCommandSlotFrameOffset(view, base),
  }
}

/**
 * What the engine has to say about the block it has just rendered, written into
 * its own unshared memory. The glue reads it once `process` has returned and
 * publishes what the interface needs into `meter_block`. The engine never sees
 * the published copy.
 */
export const EngineReportOffsets = {
  positionFrames: 0,
  peakAmpMicro: 4,
  transportState: 8,
  droppedCommands: 12,
} as const
export const ENGINE_REPORT_SIZE = 16

/** The playhead at the end of this block, in frames from the start of the timeline. */
export function readEngineReportPositionFrames(view: DataView, base: number): number {
  return view.getInt32(base, true)
}

/** The playhead at the end of this block, in frames from the start of the timeline. */
export function writeEngineReportPositionFrames(view: DataView, base: number, value: number): void {
  view.setInt32(base, value, true)
}

/**
 * The largest sample of this block, over both channels, as an amplitude times a
 * million: 1.0 is 1000000. Linear and not dBFS, because `core` has no logarithm
 * and the curve to draw is the interface's to choose.
 */
export function readEngineReportPeakAmpMicro(view: DataView, base: number): number {
  return view.getInt32(base + 4, true)
}

/**
 * The largest sample of this block, over both channels, as an amplitude times a
 * million: 1.0 is 1000000. Linear and not dBFS, because `core` has no logarithm
 * and the curve to draw is the interface's to choose.
 */
export function writeEngineReportPeakAmpMicro(view: DataView, base: number, value: number): void {
  view.setInt32(base + 4, value, true)
}

/** The transport as this block left it, one of the `transport_state` codes. */
export function readEngineReportTransportState(view: DataView, base: number): number {
  return view.getInt32(base + 8, true)
}

/** The transport as this block left it, one of the `transport_state` codes. */
export function writeEngineReportTransportState(view: DataView, base: number, value: number): void {
  view.setInt32(base + 8, value, true)
}

/**
 * How many of this block's commands the engine dropped, whatever the reason. Per
 * block rather than cumulative: the host logs it and the count starts again.
 */
export function readEngineReportDroppedCommands(view: DataView, base: number): number {
  return view.getUint32(base + 12, true)
}

/**
 * How many of this block's commands the engine dropped, whatever the reason. Per
 * block rather than cumulative: the host logs it and the count starts again.
 */
export function writeEngineReportDroppedCommands(view: DataView, base: number, value: number): void {
  view.setUint32(base + 12, value, true)
}

/** Cold path: a snapshot of `engine_report`. Allocates one object. */
export function readEngineReport(view: DataView, base: number) {
  return {
    positionFrames: readEngineReportPositionFrames(view, base),
    peakAmpMicro: readEngineReportPeakAmpMicro(view, base),
    transportState: readEngineReportTransportState(view, base),
    droppedCommands: readEngineReportDroppedCommands(view, base),
  }
}

/** What the interface reads, in the shared buffer, published by the glue. */
export const MeterBlockOffsets = {
  blockCounter: 0,
  positionFrames: 4,
  peakAmpMicro: 8,
  transportState: 12,
} as const
export const METER_BLOCK_SIZE = 16

/** How many blocks the glue has published. The engine does not count blocks. */
export function loadMeterBlockBlockCounter(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, base >> 2)
}

/** How many blocks the glue has published. The engine does not count blocks. */
export function storeMeterBlockBlockCounter(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, base >> 2, value)
}

/** The playhead as of the published block, in frames from the start of the timeline. */
export function loadMeterBlockPositionFrames(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 4) >> 2)
}

/** The playhead as of the published block, in frames from the start of the timeline. */
export function storeMeterBlockPositionFrames(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 4) >> 2, value)
}

/**
 * The meter to draw, as an amplitude times a million. The glue holds and decays
 * the engine's per-block peak into this, because the interface reads about once
 * in six blocks and would otherwise miss the transients; what the interface adds
 * is the curve, not a second decay.
 */
export function loadMeterBlockPeakAmpMicro(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 8) >> 2)
}

/**
 * The meter to draw, as an amplitude times a million. The glue holds and decays
 * the engine's per-block peak into this, because the interface reads about once
 * in six blocks and would otherwise miss the transients; what the interface adds
 * is the curve, not a second decay.
 */
export function storeMeterBlockPeakAmpMicro(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 8) >> 2, value)
}

/** The transport as of the published block, one of the `transport_state` codes. */
export function loadMeterBlockTransportState(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 12) >> 2)
}

/** The transport as of the published block, one of the `transport_state` codes. */
export function storeMeterBlockTransportState(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 12) >> 2, value)
}

/** Cold path: a snapshot of `meter_block`. Allocates one object. */
export function readMeterBlock(atoms: Int32Array, base: number) {
  return {
    blockCounter: loadMeterBlockBlockCounter(atoms, base),
    positionFrames: loadMeterBlockPositionFrames(atoms, base),
    peakAmpMicro: loadMeterBlockPeakAmpMicro(atoms, base),
    transportState: loadMeterBlockTransportState(atoms, base),
  }
}

/** Writes a complete `play` slot (kind 1). Hot path: no allocation. */
export function writePlay(view: DataView, slot: number, frameOffset: number, fromFrame: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 1, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
  view.setUint32(slot + COMMAND_PAYLOAD_OFFSET, fromFrame, true)
}

/** Cold path: allocates an object. Not for use inside process(). */
export function readPlay(view: DataView, slot: number) {
  return {
    fromFrame: view.getUint32(slot + COMMAND_PAYLOAD_OFFSET, true),
  }
}

/** Writes a complete `set_tempo` slot (kind 3). Hot path: no allocation. */
export function writeSetTempo(view: DataView, slot: number, frameOffset: number, microBpm: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 3, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
  view.setUint32(slot + COMMAND_PAYLOAD_OFFSET, microBpm, true)
}

/** Cold path: allocates an object. Not for use inside process(). */
export function readSetTempo(view: DataView, slot: number) {
  return {
    microBpm: view.getUint32(slot + COMMAND_PAYLOAD_OFFSET, true),
  }
}

/** Writes a complete `stop` slot (kind 2). Hot path: no allocation. */
export function writeStop(view: DataView, slot: number, frameOffset: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 2, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
}

export interface EngineExports {
  memory: WebAssembly.Memory
  abi_version(): number
  init(sampleRate: number, maxBlockFrames: number): number
  command_staging_ptr(): number
  command_staging_capacity(): number
  audio_out_ptr(): number
  /** Where the engine writes its report. Stable for the life of the instance, so the glue takes its view once. */
  engine_report_ptr(): number
  /**
   * Renders one block. The glue has copied `command_count` slots into the staging
   * area, in non-decreasing `frame_offset`, each of them below `frames`; `frames`
   * is at most as many as a plane of `audio_out` holds.
   *
   * An error is a report, not control flow: a command the engine cannot use is
   * dropped and counted in `engine_report.dropped_commands`, the block is rendered
   * regardless, and what comes back is the first code raised (ADR-0002).
   */
  process(commandCount: number, frames: number): number
}
