// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.
// SPDX-License-Identifier: Apache-2.0
//
// The boundary between the engine and the TypeScript half.
// Every multi-byte read and write below passes the little-endian flag.
// Atomic accessors take an Int32Array and a byte offset that must be
// 4-byte aligned; the generator refuses any field where it is not.

export const ABI_MAJOR = 0
export const ABI_HASH = 0xb79977ee
export const ABI_VERSION = 0x009977ee

export const COMMAND_PAYLOAD_OFFSET = 8
export const COMMAND_PAYLOAD_SIZE = 24

export const CommandKind = {
  play: 1,
  stop: 2,
  setTempo: 3,
} as const
export type CommandKindCode = (typeof CommandKind)[keyof typeof CommandKind]

export const EngineError = {
  ok: 0,
  unknownCommandKind: 1,
  badFrameCount: 2,
} as const
export type EngineErrorCode = (typeof EngineError)[keyof typeof EngineError]

export const TransportState = {
  stopped: 0,
  playing: 1,
} as const
export type TransportStateCode = (typeof TransportState)[keyof typeof TransportState]

/**
 * The block the engine renders into, in its own unshared memory. One run of
 * samples per channel at a fixed offset: Web Audio hands the worklet a
 * Float32Array per channel, and an offset is one number rather than a stride each
 * side works out for itself. A block fills the first `frames` samples of each
 * plane and leaves the rest of it as the previous block left it.
 */
export const AudioOutOffsets = {
  left: 0,
  right: 4096,
} as const
export const AUDIO_OUT_SIZE = 8192

/** The left channel, as long as the largest block the engine accepts. */
export const AUDIO_OUT_LEFT_LENGTH = 1024

/**
 * The left channel, as long as the largest block the engine accepts.
 * A `Float32Array` over `left` of `audio_out`. Cold path: the view is an allocation, so take it once and keep it. `base` must be a multiple of 4.
 */
export function audioOutLeft(buffer: ArrayBufferLike, base: number): Float32Array {
  return new Float32Array(buffer, base, AUDIO_OUT_LEFT_LENGTH)
}

/** The right channel, as long as the largest block the engine accepts. */
export const AUDIO_OUT_RIGHT_LENGTH = 1024

/**
 * The right channel, as long as the largest block the engine accepts.
 * A `Float32Array` over `right` of `audio_out`. Cold path: the view is an allocation, so take it once and keep it. `base` must be a multiple of 4.
 */
export function audioOutRight(buffer: ArrayBufferLike, base: number): Float32Array {
  return new Float32Array(buffer, base + 4096, AUDIO_OUT_RIGHT_LENGTH)
}

export const CommandSlotOffsets = {
  kind: 0,
  frameOffset: 4,
  payload: 8,
} as const
export const COMMAND_SLOT_SIZE = 32

export function readCommandSlotKind(view: DataView, base: number): number {
  return view.getUint32(base, true)
}

export function writeCommandSlotKind(view: DataView, base: number, value: number): void {
  view.setUint32(base, value, true)
}

export function readCommandSlotFrameOffset(view: DataView, base: number): number {
  return view.getUint32(base + 4, true)
}

export function writeCommandSlotFrameOffset(view: DataView, base: number, value: number): void {
  view.setUint32(base + 4, value, true)
}

export const COMMAND_SLOT_PAYLOAD_LENGTH = 24

/** A `Uint8Array` over `payload` of `command_slot`. Cold path: the view is an allocation, so take it once and keep it. */
export function commandSlotPayload(buffer: ArrayBufferLike, base: number): Uint8Array {
  return new Uint8Array(buffer, base + 8, COMMAND_SLOT_PAYLOAD_LENGTH)
}

/** Cold path: a snapshot of `command_slot`. Allocates one object. */
export function readCommandSlot(view: DataView, base: number) {
  return {
    kind: readCommandSlotKind(view, base),
    frameOffset: readCommandSlotFrameOffset(view, base),
  }
}

export const MeterBlockOffsets = {
  blockCounter: 0,
  positionFrames: 4,
  peakMicro: 8,
  transportState: 12,
} as const
export const METER_BLOCK_SIZE = 16

export function loadMeterBlockBlockCounter(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, base >> 2)
}

export function storeMeterBlockBlockCounter(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, base >> 2, value)
}

export function loadMeterBlockPositionFrames(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 4) >> 2)
}

export function storeMeterBlockPositionFrames(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 4) >> 2, value)
}

export function loadMeterBlockPeakMicro(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 8) >> 2)
}

export function storeMeterBlockPeakMicro(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 8) >> 2, value)
}

export function loadMeterBlockTransportState(atoms: Int32Array, base: number): number {
  return Atomics.load(atoms, (base + 12) >> 2)
}

export function storeMeterBlockTransportState(atoms: Int32Array, base: number, value: number): void {
  Atomics.store(atoms, (base + 12) >> 2, value)
}

/** Cold path: a snapshot of `meter_block`. Allocates one object. */
export function readMeterBlock(atoms: Int32Array, base: number) {
  return {
    blockCounter: loadMeterBlockBlockCounter(atoms, base),
    positionFrames: loadMeterBlockPositionFrames(atoms, base),
    peakMicro: loadMeterBlockPeakMicro(atoms, base),
    transportState: loadMeterBlockTransportState(atoms, base),
  }
}

/** Writes a complete `play` slot (kind 1). Hot path: no allocation. */
export function writePlay(view: DataView, slot: number, frameOffset: number, fromFrame: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 1, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
  view.setUint32(slot + COMMAND_PAYLOAD_OFFSET, fromFrame, true)
}

/** Cold path: allocates an object. Not for use inside process(). */
export function readPlay(view: DataView, slot: number) {
  return {
    fromFrame: view.getUint32(slot + COMMAND_PAYLOAD_OFFSET, true),
  }
}

/** Writes a complete `set_tempo` slot (kind 3). Hot path: no allocation. */
export function writeSetTempo(view: DataView, slot: number, frameOffset: number, microBpm: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 3, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
  view.setUint32(slot + COMMAND_PAYLOAD_OFFSET, microBpm, true)
}

/** Cold path: allocates an object. Not for use inside process(). */
export function readSetTempo(view: DataView, slot: number) {
  return {
    microBpm: view.getUint32(slot + COMMAND_PAYLOAD_OFFSET, true),
  }
}

/** Writes a complete `stop` slot (kind 2). Hot path: no allocation. */
export function writeStop(view: DataView, slot: number, frameOffset: number): void {
  view.setUint32(slot + CommandSlotOffsets.kind, 2, true)
  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)
  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {
    view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)
  }
}

export interface EngineExports {
  memory: WebAssembly.Memory
  abi_version(): number
  init(sampleRate: number, maxBlockFrames: number): number
  command_staging_ptr(): number
  command_staging_capacity(): number
  audio_out_ptr(): number
  meter_block_ptr(): number
  process(commandCount: number, frames: number): number
}
