// SPDX-License-Identifier: AGPL-3.0-only
//
// The Rust half of the boundary.
//
// A record is a map of memory: it is reinterpreted from bytes, so every offset
// the schema states is repeated here as a static assertion and a disagreement
// between the schema and rustc is a build error rather than a click in the
// audio (ADR-0013).
//
// A command is a value: `read` and `write` marshal it field by field at the
// schema's offsets, so the struct's own layout carries no meaning and is not
// asserted (ADR-0017).

use crate::names::{pascal, screaming};
use crate::schema::{ExportKind, Field, Schema};
use std::fmt::Write as _;

pub fn emit(schema: &Schema, abi_version: u32, abi_hash: u32) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         //\n\
         // The boundary between the engine and the TypeScript half, in Rust.\n\
         // Regenerate after any change to the schema; CI fails on a difference.\n\
         \n\
         #![allow(dead_code)]\n"
    );

    // size_of has been in the prelude since 1.80; offset_of! is a macro and is
    // not, so it is imported rather than written out at every assertion. Only
    // records assert offsets, so only records can call for the import.
    let asserts_offsets = schema
        .records
        .values()
        .any(|record| !record.fields.is_empty());
    if asserts_offsets {
        let _ = writeln!(out, "use core::mem::offset_of;\n");
    }

    let _ = writeln!(out, "pub const ABI_MAJOR: u32 = {};", schema.abi.major);
    let _ = writeln!(out, "pub const ABI_HASH: u32 = {abi_hash:#010x};");
    let _ = writeln!(out, "pub const ABI_VERSION: u32 = {abi_version:#010x};\n");

    for (name, value) in &schema.constants {
        let _ = writeln!(out, "pub const {}: usize = {value};", screaming(name));
    }
    out.push('\n');

    for (name, variants) in &schema.enums {
        let type_name = pascal(name);
        let variants = by_code(variants);
        let _ = writeln!(
            out,
            "#[repr(u32)]\n#[derive(Clone, Copy, PartialEq, Eq, Debug)]\npub enum {type_name} {{"
        );
        for (variant, code) in &variants {
            let _ = writeln!(out, "    {} = {code},", pascal(variant));
        }
        let _ = writeln!(out, "}}\n\nimpl {type_name} {{");
        let _ = writeln!(
            out,
            "    pub fn from_code(code: u32) -> Option<Self> {{\n        match code {{"
        );
        for (variant, code) in &variants {
            let _ = writeln!(
                out,
                "            {code} => Some(Self::{}),",
                pascal(variant)
            );
        }
        let _ = writeln!(
            out,
            "            _ => None,\n        }}\n    }}\n\n    pub fn code(self) -> u32 {{\n        self as u32\n    }}\n}}\n"
        );
    }

    for (name, record) in &schema.records {
        let type_name = pascal(name);
        let _ = writeln!(
            out,
            "#[repr(C)]\n#[derive(Clone, Copy, PartialEq, Debug)]\npub struct {type_name} {{"
        );
        for field in &record.fields {
            let _ = writeln!(out, "    pub {}: {},", field.name, field.rust_type());
        }
        let _ = writeln!(out, "}}\n");

        let _ = writeln!(out, "impl {type_name} {{");
        for field in &record.fields {
            let _ = writeln!(
                out,
                "    pub const {}_OFFSET: usize = {};",
                screaming(&field.name),
                field.offset
            );
        }
        let _ = writeln!(out, "    pub const SIZE: usize = {};\n}}\n", record.size);

        let _ = writeln!(
            out,
            "const _: () = assert!(size_of::<{type_name}>() == {});",
            record.size
        );
        for field in &record.fields {
            let _ = writeln!(
                out,
                "const _: () = assert!(offset_of!({type_name}, {}) == {});",
                field.name, field.offset
            );
        }
        out.push('\n');
    }

    let payload_size = schema.constant("command_payload_size").unwrap_or_default();
    for (name, command) in &schema.commands {
        let type_name = pascal(name);
        let kind = schema
            .enums
            .get("command_kind")
            .and_then(|kinds| kinds.get(name))
            .copied()
            .unwrap_or_default();

        // `derive(Default)` cannot reach an array longer than 32, so a command
        // holding one gets the impl written out instead.
        let written_default = command.fields.iter().any(Field::needs_written_default);
        let derives = if written_default {
            "Clone, Copy, PartialEq, Debug"
        } else {
            "Clone, Copy, PartialEq, Debug, Default"
        };

        let _ = writeln!(
            out,
            "/// Command `{name}`, code {kind}, read from and written to a slot's payload."
        );
        let _ = writeln!(
            out,
            "#[repr(C)]\n#[derive({derives})]\npub struct {type_name} {{"
        );
        for field in &command.fields {
            let _ = writeln!(out, "    pub {}: {},", field.name, field.rust_type());
        }
        let _ = writeln!(out, "}}\n");

        if written_default {
            let _ = writeln!(
                out,
                "impl Default for {type_name} {{\n    fn default() -> Self {{\n        Self {{"
            );
            for field in &command.fields {
                let _ = writeln!(out, "            {}: {},", field.name, field.rust_zero());
            }
            let _ = writeln!(out, "        }}\n    }}\n}}\n");
        }

        let _ = writeln!(out, "impl {type_name} {{");
        let _ = writeln!(
            out,
            "    pub const KIND: CommandKind = CommandKind::{type_name};"
        );
        for field in &command.fields {
            let _ = writeln!(
                out,
                "    pub const {}_OFFSET: usize = {};",
                screaming(&field.name),
                field.offset
            );
        }

        let _ = writeln!(
            out,
            "\n    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {{"
        );
        if command.fields.is_empty() {
            let _ = writeln!(out, "        let _ = payload;");
        }
        let _ = writeln!(out, "        Self {{");
        for field in &command.fields {
            let _ = writeln!(out, "            {}: {},", field.name, read_value(field));
        }
        let _ = writeln!(out, "        }}\n    }}\n");

        let _ = writeln!(
            out,
            "    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {{"
        );
        if command.fields.is_empty() {
            let _ = writeln!(out, "        let _ = payload;");
        }
        for field in &command.fields {
            let _ = writeln!(out, "{}", write_statements(field));
        }
        let _ = writeln!(out, "    }}\n}}\n");

        // The size assertion stays (ADR-0015): a command must fit the payload.
        // The offset assertions do not, because nothing reads this struct as
        // memory — `read` and `write` above use the schema's offsets directly.
        let _ = writeln!(
            out,
            "const _: () = assert!(size_of::<{type_name}>() <= {payload_size});\n"
        );
    }

    let functions: Vec<&str> = schema
        .exports
        .iter()
        .filter(|export| export.kind == ExportKind::Function)
        .map(|export| export.name.as_str())
        .collect();
    let _ = writeln!(
        out,
        "/// The functions the engine must export (ADR-0015). The wasm host test\n\
         /// checks the built module against this list."
    );
    let _ = writeln!(
        out,
        "pub const EXPORT_FUNCTIONS: [&str; {}] = [",
        functions.len()
    );
    for name in &functions {
        let _ = writeln!(out, "    \"{name}\",");
    }
    let _ = writeln!(out, "];");

    out
}

/// `payload[4], payload[5], …` for a value starting at a literal offset.
fn bytes_at(offset: usize, size: usize) -> String {
    (0..size)
        .map(|i| format!("payload[{}]", offset + i))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The same for a value starting at the loop's `at`.
fn bytes_from_at(size: usize) -> String {
    (0..size)
        .map(|i| {
            if i == 0 {
                "payload[at]".to_owned()
            } else {
                format!("payload[at + {i}]")
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Where element `i` of an array field begins. Written so that neither `+ 0`
/// nor `* 1` reaches the output: clippy denies both and CI runs it with
/// `-D warnings`.
fn element_at(field: &Field) -> String {
    let stride = field.ty.size();
    match (field.offset, stride) {
        (0, 1) => "i".to_owned(),
        (0, _) => format!("i * {stride}"),
        (offset, 1) => format!("{offset} + i"),
        (offset, _) => format!("{offset} + i * {stride}"),
    }
}

/// The expression that reads one field out of `payload`. A single byte has no
/// byte order, so it is taken directly rather than through `from_le_bytes`.
fn read_value(field: &Field) -> String {
    let size = field.ty.size();
    let ty = field.ty.rust();
    if !field.is_array() {
        return if size == 1 {
            format!("payload[{}]", field.offset)
        } else {
            format!("{ty}::from_le_bytes([{}])", bytes_at(field.offset, size))
        };
    }

    let element = if size == 1 {
        "payload[at]".to_owned()
    } else {
        format!("{ty}::from_le_bytes([{}])", bytes_from_at(size))
    };
    // `iter_mut().enumerate()` rather than `for i in 0..n`, which clippy
    // rejects as needless_range_loop when the index is used to index.
    format!(
        "{{\nlet mut out = {};\nfor (i, element) in out.iter_mut().enumerate() {{\nlet at = {};\n*element = {element};\n}}\nout\n}}",
        field.rust_zero(),
        element_at(field)
    )
}

/// The statements that write one field into `payload`.
fn write_statements(field: &Field) -> String {
    let size = field.ty.size();
    if !field.is_array() {
        if size == 1 {
            return format!("payload[{}] = self.{};", field.offset, field.name);
        }
        let mut out = format!("let bytes = self.{}.to_le_bytes();\n", field.name);
        for i in 0..size {
            let _ = writeln!(out, "payload[{}] = bytes[{i}];", field.offset + i);
        }
        return out;
    }

    let body = if size == 1 {
        "payload[at] = *element;".to_owned()
    } else {
        let mut out = String::from("let bytes = element.to_le_bytes();\n");
        for i in 0..size {
            let index = if i == 0 {
                "at".to_owned()
            } else {
                format!("at + {i}")
            };
            let _ = writeln!(out, "payload[{index}] = bytes[{i}];");
        }
        out
    };
    format!(
        "for (i, element) in self.{}.iter().enumerate() {{\nlet at = {};\n{body}\n}}",
        field.name,
        element_at(field)
    )
}

/// Enum variants read best in code order, which is not the alphabetical order
/// the schema is parsed into.
fn by_code(variants: &std::collections::BTreeMap<String, u32>) -> Vec<(&String, u32)> {
    let mut sorted: Vec<(&String, u32)> = variants.iter().map(|(k, v)| (k, *v)).collect();
    sorted.sort_by_key(|(_, code)| *code);
    sorted
}
