// SPDX-License-Identifier: AGPL-3.0-only
//
// The TypeScript half of the boundary. Two things this emitter exists to get
// right, because both are wrong exactly once when written by hand (ADR-0013):
// DataView defaults to big-endian while wasm is little-endian, and atomic
// fields are reached through an Int32Array whose index counts elements.

use crate::names::{camel, pascal, screaming};
use crate::schema::{ExportKind, Schema};
use std::fmt::Write as _;

/// `base + 0` is noise, and generated code is committed to be read (ADR-0013).
fn addend(offset: usize) -> String {
    if offset == 0 {
        String::new()
    } else {
        format!(" + {offset}")
    }
}

/// The Atomics index counts elements, so the byte offset is divided by four.
/// The schema check guarantees the field is aligned to make that exact.
fn atomic_index(offset: usize) -> String {
    if offset == 0 {
        "base >> 2".to_owned()
    } else {
        format!("(base + {offset}) >> 2")
    }
}

pub fn emit(schema: &Schema, abi_version: u32, abi_hash: u32) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         //\n\
         // The boundary between the engine and the TypeScript half.\n\
         // Every read and write below passes the little-endian flag explicitly.\n\
         // Atomic accessors take an Int32Array and a byte offset that must be\n\
         // 4-byte aligned; the generator refuses any field where it is not.\n"
    );

    let _ = writeln!(out, "export const ABI_MAJOR = {}", schema.abi.major);
    let _ = writeln!(out, "export const ABI_HASH = {abi_hash:#010x}");
    let _ = writeln!(out, "export const ABI_VERSION = {abi_version:#010x}\n");

    for (name, value) in &schema.constants {
        let _ = writeln!(out, "export const {} = {value}", screaming(name));
    }
    out.push('\n');

    for (name, variants) in &schema.enums {
        let type_name = pascal(name);
        let mut variants: Vec<(&String, u32)> = variants.iter().map(|(k, v)| (k, *v)).collect();
        variants.sort_by_key(|(_, code)| *code);
        let _ = writeln!(out, "export const {type_name} = {{");
        for (variant, code) in &variants {
            let _ = writeln!(out, "  {}: {code},", camel(variant));
        }
        let _ = writeln!(out, "}} as const");
        let _ = writeln!(
            out,
            "export type {type_name}Code = (typeof {type_name})[keyof typeof {type_name}]\n"
        );
    }

    for (name, record) in &schema.records {
        let type_name = pascal(name);
        let _ = writeln!(out, "export const {type_name}Offsets = {{");
        for field in &record.fields {
            let _ = writeln!(out, "  {}: {},", camel(&field.name), field.offset);
        }
        let _ = writeln!(out, "}} as const");
        let _ = writeln!(
            out,
            "export const {}_SIZE = {}\n",
            screaming(name),
            record.size
        );

        for field in &record.fields {
            if field.is_array() {
                continue;
            }
            let field_name = pascal(&field.name);
            let offset = field.offset;
            let at = addend(offset);
            if field.atomic {
                let index = atomic_index(offset);
                let _ = writeln!(
                    out,
                    "export function load{type_name}{field_name}(atoms: Int32Array, base: number): number {{\n  \
                     return Atomics.load(atoms, {index})\n}}\n"
                );
                let _ = writeln!(
                    out,
                    "export function store{type_name}{field_name}(atoms: Int32Array, base: number, value: number): void {{\n  \
                     Atomics.store(atoms, {index}, value)\n}}\n"
                );
            } else {
                let suffix = field.ty.view_suffix();
                let _ = writeln!(
                    out,
                    "export function read{type_name}{field_name}(view: DataView, base: number): number {{\n  \
                     return view.get{suffix}(base{at}, true)\n}}\n"
                );
                let _ = writeln!(
                    out,
                    "export function write{type_name}{field_name}(view: DataView, base: number, value: number): void {{\n  \
                     view.set{suffix}(base{at}, value, true)\n}}\n"
                );
            }
        }
    }

    for (name, command) in &schema.commands {
        let type_name = pascal(name);
        let kind = schema
            .enums
            .get("command_kind")
            .and_then(|kinds| kinds.get(name))
            .copied()
            .unwrap_or_default();

        let params: Vec<String> = command
            .fields
            .iter()
            .map(|field| format!("{}: number", camel(&field.name)))
            .collect();
        let signature = if params.is_empty() {
            String::new()
        } else {
            format!(", {}", params.join(", "))
        };

        let _ = writeln!(
            out,
            "/** Writes a complete `{name}` slot (kind {kind}). Hot path: no allocation. */"
        );
        let _ = writeln!(
            out,
            "export function write{type_name}(view: DataView, slot: number, frameOffset: number{signature}): void {{"
        );
        let _ = writeln!(
            out,
            "  view.setUint32(slot + CommandSlotOffsets.kind, {kind}, true)"
        );
        let _ = writeln!(
            out,
            "  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)"
        );
        for field in &command.fields {
            let suffix = field.ty.view_suffix();
            let _ = writeln!(
                out,
                "  view.set{suffix}(slot + COMMAND_PAYLOAD_OFFSET{}, {}, true)",
                addend(field.offset),
                camel(&field.name)
            );
        }
        let _ = writeln!(out, "}}\n");

        let readers: Vec<String> = command
            .fields
            .iter()
            .map(|field| {
                format!(
                    "    {}: view.get{}(slot + COMMAND_PAYLOAD_OFFSET{}, true),",
                    camel(&field.name),
                    field.ty.view_suffix(),
                    addend(field.offset)
                )
            })
            .collect();
        if command.fields.is_empty() {
            continue;
        }
        let _ = writeln!(
            out,
            "/** Cold path: allocates an object. Not for use inside process(). */"
        );
        let _ = writeln!(
            out,
            "export function read{type_name}(view: DataView, slot: number) {{\n  return {{"
        );
        for reader in readers {
            let _ = writeln!(out, "{reader}");
        }
        let _ = writeln!(out, "  }}\n}}\n");
    }

    let _ = writeln!(out, "export interface EngineExports {{");
    for export in &schema.exports {
        match export.kind {
            ExportKind::Memory => {
                let _ = writeln!(out, "  {}: WebAssembly.Memory", export.name);
            }
            ExportKind::Function => {
                let params: Vec<String> = export
                    .params
                    .iter()
                    .map(|param| format!("{}: number", camel(&param.name)))
                    .collect();
                let returns = if export.returns.is_some() {
                    "number"
                } else {
                    "void"
                };
                let _ = writeln!(out, "  {}({}): {returns}", export.name, params.join(", "));
            }
        }
    }
    let _ = writeln!(out, "}}");

    out
}
