// SPDX-License-Identifier: AGPL-3.0-only
//
// The Rust half of the boundary. A record is a map of memory, so its offsets
// are repeated as static assertions and rustc has the final word (ADR-0013).
// A command is a value, marshalled field by field, so its layout is not
// asserted (ADR-0017).

use crate::names::{pascal, screaming};
use crate::schema::{Documented, ExportKind, Field, Schema};
use std::fmt::Write as _;

pub fn emit(schema: &Schema, abi_version: u32, abi_hash: u32) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         //\n\
         // The boundary between the engine and the TypeScript half, in Rust.\n\
         // Regenerate after any change to the schema; CI fails on a difference.\n\
         \n\
         #![allow(dead_code)]\n"
    );

    // offset_of! is a macro and not in the prelude. Only records assert
    // offsets, so only records call for the import.
    let asserts_offsets = schema
        .records
        .values()
        .any(|record| !record.fields.is_empty());
    if asserts_offsets {
        let _ = writeln!(out, "use core::mem::offset_of;\n");
    }

    let _ = writeln!(out, "pub const ABI_MAJOR: u32 = {};", schema.abi.major);
    let _ = writeln!(out, "pub const ABI_HASH: u32 = {abi_hash:#010x};");
    let _ = writeln!(out, "pub const ABI_VERSION: u32 = {abi_version:#010x};\n");

    for (name, constant) in &schema.constants {
        emit_doc(&mut out, "", constant.doc.as_deref());
        let _ = writeln!(
            out,
            "pub const {}: usize = {};",
            screaming(name),
            constant.value
        );
    }
    out.push('\n');

    for (name, variants) in &schema.enums {
        let type_name = pascal(name);
        let variants = by_code(variants);
        let _ = writeln!(
            out,
            "#[repr(u32)]\n#[derive(Clone, Copy, PartialEq, Eq, Debug)]\npub enum {type_name} {{"
        );
        for (variant, code) in &variants {
            emit_doc(&mut out, "    ", code.doc.as_deref());
            let _ = writeln!(out, "    {} = {},", pascal(variant), code.value);
        }
        let _ = writeln!(out, "}}\n\nimpl {type_name} {{");
        let _ = writeln!(
            out,
            "    pub fn from_code(code: u32) -> Option<Self> {{\n        match code {{"
        );
        for (variant, code) in &variants {
            let _ = writeln!(
                out,
                "            {} => Some(Self::{}),",
                code.value,
                pascal(variant)
            );
        }
        let _ = writeln!(
            out,
            "            _ => None,\n        }}\n    }}\n\n    pub fn code(self) -> u32 {{\n        self as u32\n    }}\n}}\n"
        );
    }

    for (name, record) in &schema.records {
        let type_name = pascal(name);
        emit_doc(&mut out, "", record.doc.as_deref());
        let _ = writeln!(
            out,
            "#[repr(C)]\n#[derive(Clone, Copy, PartialEq, Debug)]\npub struct {type_name} {{"
        );
        for field in &record.fields {
            emit_doc(&mut out, "    ", field.doc.as_deref());
            let _ = writeln!(out, "    pub {}: {},", field.name, field.rust_type());
        }
        let _ = writeln!(out, "}}\n");

        let _ = writeln!(out, "impl {type_name} {{");
        for field in &record.fields {
            let _ = writeln!(
                out,
                "    pub const {}_OFFSET: usize = {};",
                screaming(&field.name),
                field.offset
            );
        }
        let _ = writeln!(out, "    pub const SIZE: usize = {};\n}}\n", record.size);

        let _ = writeln!(
            out,
            "const _: () = assert!(size_of::<{type_name}>() == {});",
            record.size
        );
        for field in &record.fields {
            let _ = writeln!(
                out,
                "const _: () = assert!(offset_of!({type_name}, {}) == {});",
                field.name, field.offset
            );
        }
        out.push('\n');
    }

    let payload_size = schema.constant("command_payload_size").unwrap_or_default();
    for (name, command) in &schema.commands {
        let type_name = pascal(name);
        let kind = schema
            .enums
            .get("command_kind")
            .and_then(|kinds| kinds.get(name))
            .map(|kind| kind.value)
            .unwrap_or_default();

        // `derive(Default)` cannot reach an array longer than 32, so a command
        // holding one gets the impl written out instead.
        let written_default = command.fields.iter().any(Field::needs_written_default);
        let derives = if written_default {
            "Clone, Copy, PartialEq, Debug"
        } else {
            "Clone, Copy, PartialEq, Debug, Default"
        };

        emit_doc(&mut out, "", command.doc.as_deref());
        let _ = writeln!(
            out,
            "/// Command `{name}`, code {kind}, read from and written to a slot's payload."
        );
        let _ = writeln!(
            out,
            "#[repr(C)]\n#[derive({derives})]\npub struct {type_name} {{"
        );
        for field in &command.fields {
            emit_doc(&mut out, "    ", field.doc.as_deref());
            let _ = writeln!(out, "    pub {}: {},", field.name, field.rust_type());
        }
        let _ = writeln!(out, "}}\n");

        if written_default {
            let _ = writeln!(
                out,
                "impl Default for {type_name} {{\n    fn default() -> Self {{\n        Self {{"
            );
            for field in &command.fields {
                let _ = writeln!(out, "            {}: {},", field.name, field.rust_zero());
            }
            let _ = writeln!(out, "        }}\n    }}\n}}\n");
        }

        let _ = writeln!(out, "impl {type_name} {{");
        let _ = writeln!(
            out,
            "    pub const KIND: CommandKind = CommandKind::{type_name};"
        );
        for field in &command.fields {
            let _ = writeln!(
                out,
                "    pub const {}_OFFSET: usize = {};",
                screaming(&field.name),
                field.offset
            );
        }

        let _ = writeln!(
            out,
            "\n    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {{"
        );
        if command.fields.is_empty() {
            let _ = writeln!(out, "        let _ = payload;");
        }
        let _ = writeln!(out, "        Self {{");
        for field in &command.fields {
            let _ = writeln!(out, "            {}: {},", field.name, read_value(field));
        }
        let _ = writeln!(out, "        }}\n    }}\n");

        let _ = writeln!(
            out,
            "    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {{"
        );
        // A slot is reused: clearing it is what keeps the previous command's
        // bytes out of this one.
        let _ = writeln!(out, "        *payload = [0u8; COMMAND_PAYLOAD_SIZE];");
        for field in &command.fields {
            let _ = writeln!(out, "{}", write_statements(field));
        }
        let _ = writeln!(out, "    }}\n}}\n");

        // No offset assertion: nothing reads this struct as memory (ADR-0017).
        let _ = writeln!(
            out,
            "const _: () = assert!(size_of::<{type_name}>() <= {payload_size});\n"
        );
    }

    let functions: Vec<&str> = schema
        .exports
        .iter()
        .filter(|export| export.kind == ExportKind::Function)
        .map(|export| export.name.as_str())
        .collect();
    let _ = writeln!(
        out,
        "/// The functions the engine must export (ADR-0015). The wasm host test\n\
         /// checks the built module against this list."
    );
    let _ = writeln!(
        out,
        "pub const EXPORT_FUNCTIONS: [&str; {}] = [",
        functions.len()
    );
    for name in &functions {
        let _ = writeln!(out, "    \"{name}\",");
    }
    let _ = writeln!(out, "];");

    out
}

/// The schema's own prose, one `///` per line its author wrote. rustfmt does
/// not rewrap a doc comment, so where the lines break is the schema's to say.
fn emit_doc(out: &mut String, indent: &str, doc: Option<&str>) {
    let Some(text) = doc else { return };
    for line in text.lines() {
        if line.is_empty() {
            let _ = writeln!(out, "{indent}///");
        } else {
            let _ = writeln!(out, "{indent}/// {line}");
        }
    }
}

fn bytes_at(offset: usize, size: usize) -> String {
    (0..size)
        .map(|i| format!("payload[{}]", offset + i))
        .collect::<Vec<_>>()
        .join(", ")
}

/// A single byte has no byte order, so it skips `from_le_bytes`.
fn read_value(field: &Field) -> String {
    let size = field.ty.size();
    let ty = field.ty.rust();
    if !field.is_array() {
        return if size == 1 {
            format!("payload[{}]", field.offset)
        } else {
            format!("{ty}::from_le_bytes([{}])", bytes_at(field.offset, size))
        };
    }

    // Unrolled, so that every index is a constant into an array of known
    // length: the compiler emits no bounds check, and there is no panic to
    // reach the audio thread (ADR-0002). A command's payload is small, so the
    // longest this can get is one line per byte of it.
    let elements: Vec<String> = (0..field.count)
        .map(|n| {
            let at = field.offset + n * size;
            if size == 1 {
                format!("payload[{at}]")
            } else {
                format!("{ty}::from_le_bytes([{}])", bytes_at(at, size))
            }
        })
        .collect();
    format!("[{}]", elements.join(", "))
}

fn write_statements(field: &Field) -> String {
    let size = field.ty.size();
    if !field.is_array() {
        if size == 1 {
            return format!("payload[{}] = self.{};", field.offset, field.name);
        }
        let mut out = format!("let bytes = self.{}.to_le_bytes();\n", field.name);
        for i in 0..size {
            let _ = writeln!(out, "payload[{}] = bytes[{i}];", field.offset + i);
        }
        return out;
    }

    let mut out = String::new();
    for n in 0..field.count {
        let at = field.offset + n * size;
        if size == 1 {
            let _ = writeln!(out, "payload[{at}] = self.{}[{n}];", field.name);
            continue;
        }
        let _ = writeln!(out, "let bytes = self.{}[{n}].to_le_bytes();", field.name);
        for i in 0..size {
            let _ = writeln!(out, "payload[{}] = bytes[{i}];", at + i);
        }
    }
    out
}

/// Enum variants read best in code order, which is not the alphabetical order
/// the schema is parsed into.
fn by_code(
    variants: &std::collections::BTreeMap<String, Documented<u32>>,
) -> Vec<(&String, &Documented<u32>)> {
    let mut sorted: Vec<(&String, &Documented<u32>)> = variants.iter().collect();
    sorted.sort_by_key(|(_, code)| code.value);
    sorted
}
