// SPDX-License-Identifier: AGPL-3.0-only
//
// The TypeScript half of the boundary. Three things this emitter exists to get
// right, because all three are wrong exactly once when written by hand
// (ADR-0013): DataView defaults to big-endian while wasm is little-endian,
// atomic fields are reached through an Int32Array whose index counts elements,
// and a field with a count is as many elements as the schema reserved bytes
// for, not one.
//
// Every DataView call for a schema field is built by `view_get` and `view_set`
// below, so the question "does this accessor take a byte-order argument?" is
// answered in one place rather than at each call. The two exceptions are the
// slot header written by each command writer, which this emitter spells out;
// the schema check pins the names and the widths it spells.

use crate::names::{camel, pascal, screaming};
use crate::schema::{ExportKind, Field, Schema, Type};
use std::fmt::Write as _;

const PAYLOAD_BASE: &str = "slot + COMMAND_PAYLOAD_OFFSET";

/// `base + 4 + i * 2`, with every `+ 0` and `* 1` left out: `base + 0` is
/// noise, and generated code is committed to be read (ADR-0013). `element`
/// carries the stride when the expression addresses element `i` of an array.
fn offset_expr(base: &str, offset: usize, element: Option<usize>) -> String {
    let mut out = base.to_owned();
    if offset != 0 {
        let _ = write!(out, " + {offset}");
    }
    match element {
        Some(1) => out.push_str(" + i"),
        Some(stride) => {
            let _ = write!(out, " + i * {stride}");
        }
        None => {}
    }
    out
}

/// `view.getUint32(<at>, true)` — or `view.getUint8(<at>)`, because one byte
/// has no byte order and the accessor takes no third argument. TypeScript
/// rejects the call that passes one, so this is not a matter of taste.
fn view_get(ty: Type, at: &str) -> String {
    if ty.view_takes_endianness() {
        format!("view.get{}({at}, true)", ty.view_suffix())
    } else {
        format!("view.get{}({at})", ty.view_suffix())
    }
}

fn view_set(ty: Type, at: &str, value: &str) -> String {
    if ty.view_takes_endianness() {
        format!("view.set{}({at}, {value}, true)", ty.view_suffix())
    } else {
        format!("view.set{}({at}, {value})", ty.view_suffix())
    }
}

/// The Atomics index counts elements, so the byte offset is divided by four.
/// The schema check guarantees the field's own offset is a multiple of four;
/// the caller's `base` has to be one too.
fn atomic_index(offset: usize) -> String {
    if offset == 0 {
        "base >> 2".to_owned()
    } else {
        format!("(base + {offset}) >> 2")
    }
}

pub fn emit(schema: &Schema, abi_version: u32, abi_hash: u32) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         //\n\
         // The boundary between the engine and the TypeScript half.\n\
         // Every multi-byte read and write below passes the little-endian flag.\n\
         // Atomic accessors take an Int32Array and a byte offset that must be\n\
         // 4-byte aligned; the generator refuses any field where it is not.\n"
    );

    let _ = writeln!(out, "export const ABI_MAJOR = {}", schema.abi.major);
    let _ = writeln!(out, "export const ABI_HASH = {abi_hash:#010x}");
    let _ = writeln!(out, "export const ABI_VERSION = {abi_version:#010x}\n");

    for (name, value) in &schema.constants {
        let _ = writeln!(out, "export const {} = {value}", screaming(name));
    }
    out.push('\n');

    for (name, variants) in &schema.enums {
        let type_name = pascal(name);
        let mut variants: Vec<(&String, u32)> = variants.iter().map(|(k, v)| (k, *v)).collect();
        variants.sort_by_key(|(_, code)| *code);
        let _ = writeln!(out, "export const {type_name} = {{");
        for (variant, code) in &variants {
            let _ = writeln!(out, "  {}: {code},", camel(variant));
        }
        let _ = writeln!(out, "}} as const");
        let _ = writeln!(
            out,
            "export type {type_name}Code = (typeof {type_name})[keyof typeof {type_name}]\n"
        );
    }

    for (name, record) in &schema.records {
        let type_name = pascal(name);
        let _ = writeln!(out, "export const {type_name}Offsets = {{");
        for field in &record.fields {
            let _ = writeln!(out, "  {}: {},", camel(&field.name), field.offset);
        }
        let _ = writeln!(out, "}} as const");
        let _ = writeln!(
            out,
            "export const {}_SIZE = {}\n",
            screaming(name),
            record.size
        );

        for field in &record.fields {
            // An array field of a record gets no accessor. Copying it would be
            // wrong for the one that exists — a slot's payload is written by
            // the command writers below — and the offset above is what a caller
            // needs to take its own view.
            if field.is_array() {
                continue;
            }
            let field_name = pascal(&field.name);
            let at = offset_expr("base", field.offset, None);
            if field.atomic {
                let index = atomic_index(field.offset);
                let _ = writeln!(
                    out,
                    "export function load{type_name}{field_name}(atoms: Int32Array, base: number): number {{\n  \
                     return Atomics.load(atoms, {index})\n}}\n"
                );
                let _ = writeln!(
                    out,
                    "export function store{type_name}{field_name}(atoms: Int32Array, base: number, value: number): void {{\n  \
                     Atomics.store(atoms, {index}, value)\n}}\n"
                );
            } else {
                let _ = writeln!(
                    out,
                    "export function read{type_name}{field_name}(view: DataView, base: number): number {{\n  \
                     return {}\n}}\n",
                    view_get(field.ty, &at)
                );
                let _ = writeln!(
                    out,
                    "export function write{type_name}{field_name}(view: DataView, base: number, value: number): void {{\n  \
                     {}\n}}\n",
                    view_set(field.ty, &at, "value")
                );
            }
        }
    }

    for (name, command) in &schema.commands {
        let type_name = pascal(name);
        let kind = schema
            .enums
            .get("command_kind")
            .and_then(|kinds| kinds.get(name))
            .copied()
            .unwrap_or_default();

        // An array field is a loop, so it gets a function of its own rather
        // than being inlined into the slot writer twice over.
        for field in &command.fields {
            if !field.is_array() {
                continue;
            }
            emit_array_field(&mut out, &type_name, name, field);
        }

        let params: Vec<String> = command
            .fields
            .iter()
            .map(|field| format!("{}: {}", camel(&field.name), field.ts_type()))
            .collect();
        let signature = if params.is_empty() {
            String::new()
        } else {
            format!(", {}", params.join(", "))
        };

        let _ = writeln!(
            out,
            "/** Writes a complete `{name}` slot (kind {kind}). Hot path: no allocation. */"
        );
        let _ = writeln!(
            out,
            "export function write{type_name}(view: DataView, slot: number, frameOffset: number{signature}): void {{"
        );
        let _ = writeln!(
            out,
            "  view.setUint32(slot + CommandSlotOffsets.kind, {kind}, true)"
        );
        let _ = writeln!(
            out,
            "  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)"
        );
        // A slot is reused, so the payload is cleared before the fields are
        // written over it. The stride of four is safe because the schema check
        // makes the slot size and the payload offset multiples of eight, and
        // the payload is the difference between them.
        let _ = writeln!(
            out,
            "  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {{\n    \
             view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)\n  }}"
        );
        for field in &command.fields {
            let value = camel(&field.name);
            if field.is_array() {
                let _ = writeln!(
                    out,
                    "  write{type_name}{}(view, slot, {value})",
                    pascal(&field.name)
                );
            } else {
                let at = offset_expr(PAYLOAD_BASE, field.offset, None);
                let _ = writeln!(out, "  {}", view_set(field.ty, &at, &value));
            }
        }
        let _ = writeln!(out, "}}\n");

        if command.fields.is_empty() {
            continue;
        }
        let _ = writeln!(
            out,
            "/** Cold path: allocates an object. Not for use inside process(). */"
        );
        let _ = writeln!(
            out,
            "export function read{type_name}(view: DataView, slot: number) {{\n  return {{"
        );
        for field in &command.fields {
            let value = if field.is_array() {
                format!("read{type_name}{}(view, slot)", pascal(&field.name))
            } else {
                view_get(field.ty, &offset_expr(PAYLOAD_BASE, field.offset, None))
            };
            let _ = writeln!(out, "    {}: {value},", camel(&field.name));
        }
        let _ = writeln!(out, "  }}\n}}\n");
    }

    let _ = writeln!(out, "export interface EngineExports {{");
    for export in &schema.exports {
        match export.kind {
            ExportKind::Memory => {
                let _ = writeln!(out, "  {}: WebAssembly.Memory", export.name);
            }
            ExportKind::Function => {
                let params: Vec<String> = export
                    .params
                    .iter()
                    .map(|param| format!("{}: number", camel(&param.name)))
                    .collect();
                let returns = if export.returns.is_some() {
                    "number"
                } else {
                    "void"
                };
                let _ = writeln!(out, "  {}({}): {returns}", export.name, params.join(", "));
            }
        }
    }
    let _ = writeln!(out, "}}");

    out
}

/// The reader and writer for one array field of a command. The writer fills
/// every byte the schema reserved: an element the caller left out is written
/// as zero rather than leaving whatever the previous command put there.
fn emit_array_field(out: &mut String, type_name: &str, command: &str, field: &Field) {
    let field_name = pascal(&field.name);
    let value = camel(&field.name);
    let array = field.ty.ts_array();
    let count = field.count;
    let at = offset_expr(PAYLOAD_BASE, field.offset, Some(field.ty.size()));

    let _ = writeln!(
        out,
        "/** Copies `{}` into a `{command}` slot, zero-filling anything the\n \
         * caller left short. Hot path: no allocation. */",
        field.name
    );
    let _ = writeln!(
        out,
        "export function write{type_name}{field_name}(view: DataView, slot: number, {value}: {array}): void {{\n  \
         for (let i = 0; i < {count}; i++) {{\n    {}\n  }}\n}}\n",
        view_set(field.ty, &at, &format!("{value}[i] ?? 0"))
    );
    let _ = writeln!(
        out,
        "/** Cold path: allocates. */\n\
         export function read{type_name}{field_name}(view: DataView, slot: number): {array} {{\n  \
         const out = new {array}({count})\n  \
         for (let i = 0; i < {count}; i++) {{\n    out[i] = {}\n  }}\n  \
         return out\n}}\n",
        view_get(field.ty, &at)
    );
}
