// SPDX-License-Identifier: AGPL-3.0-only
//
// The Rust half of the boundary. Every offset the schema states is repeated
// here as a static assertion, so that a disagreement between the schema and
// rustc is a build error rather than a click in the audio (ADR-0013).

use crate::names::{pascal, screaming};
use crate::schema::{ExportKind, Schema};
use std::fmt::Write as _;

pub fn emit(schema: &Schema, abi_version: u32, abi_hash: u32) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         //\n\
         // The boundary between the engine and the TypeScript half, in Rust.\n\
         // Regenerate after any change to the schema; CI fails on a difference.\n\
         \n\
         #![allow(dead_code)]\n"
    );

    let _ = writeln!(out, "pub const ABI_MAJOR: u32 = {};", schema.abi.major);
    let _ = writeln!(out, "pub const ABI_HASH: u32 = {abi_hash:#010x};");
    let _ = writeln!(out, "pub const ABI_VERSION: u32 = {abi_version:#010x};\n");

    for (name, value) in &schema.constants {
        let _ = writeln!(out, "pub const {}: usize = {value};", screaming(name));
    }
    out.push('\n');

    for (name, variants) in &schema.enums {
        let type_name = pascal(name);
        let variants = by_code(variants);
        let _ = writeln!(
            out,
            "#[repr(u32)]\n#[derive(Clone, Copy, PartialEq, Eq, Debug)]\npub enum {type_name} {{"
        );
        for (variant, code) in &variants {
            let _ = writeln!(out, "    {} = {code},", pascal(variant));
        }
        let _ = writeln!(out, "}}\n\nimpl {type_name} {{");
        let _ = writeln!(
            out,
            "    pub fn from_code(code: u32) -> Option<Self> {{\n        match code {{"
        );
        for (variant, code) in &variants {
            let _ = writeln!(
                out,
                "            {code} => Some(Self::{}),",
                pascal(variant)
            );
        }
        let _ = writeln!(
            out,
            "            _ => None,\n        }}\n    }}\n\n    pub fn code(self) -> u32 {{\n        self as u32\n    }}\n}}\n"
        );
    }

    for (name, record) in &schema.records {
        let type_name = pascal(name);
        let _ = writeln!(
            out,
            "#[repr(C)]\n#[derive(Clone, Copy, PartialEq, Debug)]\npub struct {type_name} {{"
        );
        for field in &record.fields {
            let ty = if field.is_array() {
                format!("[{}; {}]", field.ty.rust(), field.count)
            } else {
                field.ty.rust().to_owned()
            };
            let _ = writeln!(out, "    pub {}: {ty},", field.name);
        }
        let _ = writeln!(out, "}}\n");

        let _ = writeln!(out, "impl {type_name} {{");
        for field in &record.fields {
            let _ = writeln!(
                out,
                "    pub const {}_OFFSET: usize = {};",
                screaming(&field.name),
                field.offset
            );
        }
        let _ = writeln!(out, "    pub const SIZE: usize = {};\n}}\n", record.size);

        let _ = writeln!(
            out,
            "const _: () = assert!(core::mem::size_of::<{type_name}>() == {});",
            record.size
        );
        for field in &record.fields {
            let _ = writeln!(
                out,
                "const _: () = assert!(core::mem::offset_of!({type_name}, {}) == {});",
                field.name, field.offset
            );
        }
        out.push('\n');
    }

    let payload_size = schema.constant("command_payload_size").unwrap_or_default();
    for (name, command) in &schema.commands {
        let type_name = pascal(name);
        let kind = schema
            .enums
            .get("command_kind")
            .and_then(|kinds| kinds.get(name))
            .copied()
            .unwrap_or_default();

        let _ = writeln!(
            out,
            "/// Command `{name}`, code {kind}. Laid out from the start of a slot's payload."
        );
        let _ = writeln!(
            out,
            "#[repr(C)]\n#[derive(Clone, Copy, PartialEq, Debug, Default)]\npub struct {type_name} {{"
        );
        for field in &command.fields {
            let _ = writeln!(out, "    pub {}: {},", field.name, field.ty.rust());
        }
        let _ = writeln!(out, "}}\n");

        let _ = writeln!(out, "impl {type_name} {{");
        let _ = writeln!(
            out,
            "    pub const KIND: CommandKind = CommandKind::{type_name};"
        );
        for field in &command.fields {
            let _ = writeln!(
                out,
                "    pub const {}_OFFSET: usize = {};",
                screaming(&field.name),
                field.offset
            );
        }

        let _ = writeln!(
            out,
            "\n    pub fn read(payload: &[u8; COMMAND_PAYLOAD_SIZE]) -> Self {{"
        );
        if command.fields.is_empty() {
            let _ = writeln!(out, "        let _ = payload;");
        }
        let _ = writeln!(out, "        Self {{");
        for field in &command.fields {
            let bytes = (0..field.ty.size())
                .map(|i| format!("payload[{}]", field.offset + i))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                out,
                "            {}: {}::from_le_bytes([{bytes}]),",
                field.name,
                field.ty.rust()
            );
        }
        let _ = writeln!(out, "        }}\n    }}\n");

        let _ = writeln!(
            out,
            "    pub fn write(&self, payload: &mut [u8; COMMAND_PAYLOAD_SIZE]) {{"
        );
        if command.fields.is_empty() {
            let _ = writeln!(out, "        let _ = payload;");
        }
        for field in &command.fields {
            let _ = writeln!(
                out,
                "        let bytes = self.{}.to_le_bytes();",
                field.name
            );
            for i in 0..field.ty.size() {
                let _ = writeln!(out, "        payload[{}] = bytes[{i}];", field.offset + i);
            }
        }
        let _ = writeln!(out, "    }}\n}}\n");

        let _ = writeln!(
            out,
            "const _: () = assert!(core::mem::size_of::<{type_name}>() <= {payload_size});"
        );
        for field in &command.fields {
            let _ = writeln!(
                out,
                "const _: () = assert!(core::mem::offset_of!({type_name}, {}) == {});",
                field.name, field.offset
            );
        }
        out.push('\n');
    }

    let functions: Vec<&str> = schema
        .exports
        .iter()
        .filter(|export| export.kind == ExportKind::Function)
        .map(|export| export.name.as_str())
        .collect();
    let _ = writeln!(
        out,
        "/// The functions the engine must export (ADR-0015). The wasm host test\n\
         /// checks the built module against this list."
    );
    let _ = writeln!(
        out,
        "pub const EXPORT_FUNCTIONS: [&str; {}] = [",
        functions.len()
    );
    for name in &functions {
        let _ = writeln!(out, "    \"{name}\",");
    }
    let _ = writeln!(out, "];");

    out
}

/// Enum variants read best in code order, which is not the alphabetical order
/// the schema is parsed into.
fn by_code(variants: &std::collections::BTreeMap<String, u32>) -> Vec<(&String, u32)> {
    let mut sorted: Vec<(&String, u32)> = variants.iter().map(|(k, v)| (k, *v)).collect();
    sorted.sort_by_key(|(_, code)| *code);
    sorted
}
