// SPDX-License-Identifier: AGPL-3.0-only
//
// The TypeScript half of the boundary. Three things are wrong exactly once
// when written by hand (ADR-0013): DataView is big-endian by default, an
// Atomics index counts elements rather than bytes, and a field with a count is
// as many elements as it reserved bytes for. Every DataView call goes through
// `view_get` / `view_set`, so the byte-order question is answered once.

use crate::names::{camel, pascal, screaming};
use crate::schema::{Documented, ExportKind, Field, Record, Schema, Type};
use std::fmt::Write as _;

const PAYLOAD_BASE: &str = "slot + COMMAND_PAYLOAD_OFFSET";
const BASE: &str = "Byte offset of the record inside that memory.";
const RING_VIEW: &str = "A view over the memory the ring slot lives in.";
const SLOT_READ: &str = "Byte offset of the slot to read.";
const SLOT_WRITE: &str = "Byte offset of the slot to write.";
const ALIGNED_BASE: &str = "Byte offset of the record, itself a multiple of 4.";

fn view_over(record: &str) -> String {
    format!("A view over the memory `{record}` lives in.")
}

fn shared_array(record: &str) -> String {
    format!("An `Int32Array` over the shared buffer `{record}` lives in.")
}

/// `base + 4 + i * 2`, with every `+ 0` and `* 1` left out: generated code is
/// committed to be read (ADR-0013).
fn offset_expr(base: &str, offset: usize, element: Option<usize>) -> String {
    let mut out = base.to_owned();
    if offset != 0 {
        let _ = write!(out, " + {offset}");
    }
    match element {
        Some(1) => out.push_str(" + i"),
        Some(stride) => {
            let _ = write!(out, " + i * {stride}");
        }
        None => {}
    }
    out
}

/// `getUint8` takes no third argument, and TypeScript rejects the call that
/// passes one.
fn view_get(ty: Type, at: &str) -> String {
    if ty.view_takes_endianness() {
        format!("view.get{}({at}, true)", ty.view_suffix())
    } else {
        format!("view.get{}({at})", ty.view_suffix())
    }
}

fn view_set(ty: Type, at: &str, value: &str) -> String {
    if ty.view_takes_endianness() {
        format!("view.set{}({at}, {value}, true)", ty.view_suffix())
    } else {
        format!("view.set{}({at}, {value})", ty.view_suffix())
    }
}

/// The index counts elements. The check guarantees the field's own offset is a
/// multiple of four; the caller's `base` has to be one too.
fn atomic_index(offset: usize) -> String {
    if offset == 0 {
        "base >> 2".to_owned()
    } else {
        format!("(base + {offset}) >> 2")
    }
}

pub fn emit(schema: &Schema, abi_version: u32, abi_hash: u32) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by `cargo xtask generate` from schema/boundary.toml — do not edit.\n\
         // SPDX-License-Identifier: Apache-2.0\n\
         //\n\
         // The boundary between the engine and the TypeScript half.\n\
         // Every multi-byte read and write below passes the little-endian flag.\n\
         // Atomic accessors take an Int32Array and a byte offset that must be\n\
         // 4-byte aligned; the generator refuses any field where it is not.\n"
    );

    let _ = writeln!(
        out,
        "/** The boundary's major version, set by hand in the schema. */\n\
         export const ABI_MAJOR = {}",
        schema.abi.major
    );
    let _ = writeln!(
        out,
        "/** A hash of the schema, so that editing a field moves the version. */\n\
         export const ABI_HASH = {abi_hash:#010x}"
    );
    let _ = writeln!(
        out,
        "/**\n \
         * The version the engine module must report from `abi_version`: the major\n \
         * number in the top byte, the hash of the schema in the rest.\n \
         */\n\
         export const ABI_VERSION = {abi_version:#010x}\n"
    );

    for (name, constant) in &schema.constants {
        emit_doc(&mut out, "", constant.doc.as_deref());
        let _ = writeln!(out, "export const {} = {}", screaming(name), constant.value);
    }
    out.push('\n');

    for (name, variants) in &schema.enums {
        let type_name = pascal(name);
        let mut variants: Vec<(&String, &Documented<u32>)> = variants.iter().collect();
        variants.sort_by_key(|(_, code)| code.value);
        let _ = writeln!(
            out,
            "/** The `{name}` codes. */\nexport const {type_name} = {{"
        );
        for (variant, code) in &variants {
            emit_doc(&mut out, "  ", code.doc.as_deref());
            let _ = writeln!(out, "  {}: {},", camel(variant), code.value);
        }
        let _ = writeln!(out, "}} as const");
        let _ = writeln!(
            out,
            "/** Any one of the `{name}` codes. */\n\
             export type {type_name}Code = (typeof {type_name})[keyof typeof {type_name}]\n"
        );
    }

    for (name, record) in &schema.records {
        let type_name = pascal(name);
        let table = prose_then(
            record.doc.as_deref(),
            format!("Byte offsets of the fields of `{name}`."),
        );
        emit_block(&mut out, "", &table);
        let _ = writeln!(out, "export const {type_name}Offsets = {{");
        for field in &record.fields {
            emit_doc(&mut out, "  ", field.doc.as_deref());
            let _ = writeln!(out, "  {}: {},", camel(&field.name), field.offset);
        }
        let _ = writeln!(out, "}} as const");
        let _ = writeln!(
            out,
            "/** `{name}` in bytes. */\nexport const {}_SIZE = {}\n",
            screaming(name),
            record.size
        );

        for field in &record.fields {
            if field.is_array() {
                emit_record_array(&mut out, name, field);
                continue;
            }
            let field_name = pascal(&field.name);
            let at = offset_expr("base", field.offset, None);
            let about = |verb: &str| -> Vec<String> {
                match field.doc.as_deref() {
                    Some(text) => text.lines().map(str::to_owned).collect(),
                    None => vec![format!("{verb} `{}` of `{name}`.", field.name)],
                }
            };
            if field.atomic {
                let index = atomic_index(field.offset);

                let mut doc = about("Reads");
                doc.push(String::new());
                doc.push("Read with `Atomics.load`.".to_owned());
                param(&mut doc, "atoms", Some(&shared_array(name)));
                param(&mut doc, "base", Some(ALIGNED_BASE));
                emit_block(&mut out, "", &doc);
                let _ = writeln!(
                    out,
                    "export function load{type_name}{field_name}(atoms: Int32Array, base: number): number {{\n  \
                     return Atomics.load(atoms, {index})\n}}\n"
                );

                let mut doc = about("Writes");
                doc.push(String::new());
                doc.push("Published with `Atomics.store`.".to_owned());
                param(&mut doc, "atoms", Some(&shared_array(name)));
                param(&mut doc, "base", Some(ALIGNED_BASE));
                param(&mut doc, "value", Some("The value to publish."));
                emit_block(&mut out, "", &doc);
                let _ = writeln!(
                    out,
                    "export function store{type_name}{field_name}(atoms: Int32Array, base: number, value: number): void {{\n  \
                     Atomics.store(atoms, {index}, value)\n}}\n"
                );
            } else {
                let mut doc = about("Reads");
                param(&mut doc, "view", Some(&view_over(name)));
                param(&mut doc, "base", Some(BASE));
                emit_block(&mut out, "", &doc);
                let _ = writeln!(
                    out,
                    "export function read{type_name}{field_name}(view: DataView, base: number): number {{\n  \
                     return {}\n}}\n",
                    view_get(field.ty, &at)
                );

                let mut doc = about("Writes");
                param(&mut doc, "view", Some(&view_over(name)));
                param(&mut doc, "base", Some(BASE));
                param(&mut doc, "value", Some("The value to write."));
                emit_block(&mut out, "", &doc);
                let _ = writeln!(
                    out,
                    "export function write{type_name}{field_name}(view: DataView, base: number, value: number): void {{\n  \
                     {}\n}}\n",
                    view_set(field.ty, &at, "value")
                );
            }
        }

        emit_record_reader(&mut out, &type_name, name, record);
    }

    for (name, command) in &schema.commands {
        let type_name = pascal(name);
        let kind = schema
            .enums
            .get("command_kind")
            .and_then(|kinds| kinds.get(name))
            .map(|kind| kind.value)
            .unwrap_or_default();

        for field in &command.fields {
            if !field.is_array() {
                continue;
            }
            emit_array_field(&mut out, &type_name, name, field);
        }

        let params: Vec<String> = command
            .fields
            .iter()
            .map(|field| format!("{}: {}", camel(&field.name), field.ts_type()))
            .collect();
        let signature = if params.is_empty() {
            String::new()
        } else {
            format!(", {}", params.join(", "))
        };

        // One block, not two: TypeScript attaches only the one that touches the
        // declaration, so a second above it would be text nothing reads.
        let mut doc = prose_then(
            command.doc.as_deref(),
            format!("Writes a complete `{name}` slot (kind {kind}). Hot path: no allocation."),
        );
        param(&mut doc, "view", Some(RING_VIEW));
        param(&mut doc, "slot", Some(SLOT_WRITE));
        param(
            &mut doc,
            "frameOffset",
            slot_field_doc(schema, "frame_offset"),
        );
        for field in &command.fields {
            param(&mut doc, &camel(&field.name), field.doc.as_deref());
        }
        emit_block(&mut out, "", &doc);
        let _ = writeln!(
            out,
            "export function write{type_name}(view: DataView, slot: number, frameOffset: number{signature}): void {{"
        );
        let _ = writeln!(
            out,
            "  view.setUint32(slot + CommandSlotOffsets.kind, {kind}, true)"
        );
        let _ = writeln!(
            out,
            "  view.setUint32(slot + CommandSlotOffsets.frameOffset, frameOffset, true)"
        );
        // A slot is reused, so the payload is cleared first. The stride of
        // four is safe: the check makes the slot size and the payload offset
        // multiples of eight, and the payload is their difference.
        let _ = writeln!(
            out,
            "  for (let i = 0; i < COMMAND_PAYLOAD_SIZE; i += 4) {{\n    \
             view.setUint32(slot + COMMAND_PAYLOAD_OFFSET + i, 0, true)\n  }}"
        );
        for field in &command.fields {
            let value = camel(&field.name);
            if field.is_array() {
                let _ = writeln!(
                    out,
                    "  write{type_name}{}(view, slot, {value})",
                    pascal(&field.name)
                );
            } else {
                let at = offset_expr(PAYLOAD_BASE, field.offset, None);
                let _ = writeln!(out, "  {}", view_set(field.ty, &at, &value));
            }
        }
        let _ = writeln!(out, "}}\n");

        if command.fields.is_empty() {
            continue;
        }
        let mut doc = prose_then(
            command.doc.as_deref(),
            format!(
                "Reads a `{name}` slot back. Cold path: allocates an object, so not \
             for use inside process()."
            ),
        );
        param(&mut doc, "view", Some(RING_VIEW));
        param(&mut doc, "slot", Some(SLOT_READ));
        emit_block(&mut out, "", &doc);
        let _ = writeln!(
            out,
            "export function read{type_name}(view: DataView, slot: number) {{\n  return {{"
        );
        for field in &command.fields {
            let value = if field.is_array() {
                format!("read{type_name}{}(view, slot)", pascal(&field.name))
            } else {
                view_get(field.ty, &offset_expr(PAYLOAD_BASE, field.offset, None))
            };
            let _ = writeln!(out, "    {}: {value},", camel(&field.name));
        }
        let _ = writeln!(out, "  }}\n}}\n");
    }

    let _ = writeln!(
        out,
        "/**\n \
         * What the engine module exports, checked against the same schema the\n \
         * records come from rather than against a comment (ADR-0015).\n \
         */\n\
         export interface EngineExports {{"
    );
    for export in &schema.exports {
        emit_doc(&mut out, "  ", export.doc.as_deref());
        match export.kind {
            ExportKind::Memory => {
                let _ = writeln!(out, "  {}: WebAssembly.Memory", export.name);
            }
            ExportKind::Function => {
                let params: Vec<String> = export
                    .params
                    .iter()
                    .map(|param| format!("{}: number", camel(&param.name)))
                    .collect();
                let returns = if export.returns.is_some() {
                    "number"
                } else {
                    "void"
                };
                let _ = writeln!(out, "  {}({}): {returns}", export.name, params.join(", "));
            }
        }
    }
    let _ = writeln!(out, "}}");

    out
}

/// The schema's own prose as a JSDoc block, written once where the thing it
/// describes is declared. An accessor is an operation over a field rather than a
/// second declaration of it, so it carries nothing. Where the lines break is the
/// schema's to say.
fn emit_doc(out: &mut String, indent: &str, doc: Option<&str>) {
    let Some(text) = doc else { return };
    let lines: Vec<String> = text.lines().map(str::to_owned).collect();
    emit_block(out, indent, &lines);
}

/// A block that opens with the schema's own prose, where the schema has any,
/// and then says what the generated name does.
fn prose_then(prose: Option<&str>, about: String) -> Vec<String> {
    let mut doc: Vec<String> = Vec::new();
    if let Some(text) = prose {
        doc.extend(text.lines().map(str::to_owned));
        doc.push(String::new());
    }
    doc.push(about);
    doc
}

fn emit_block(out: &mut String, indent: &str, lines: &[String]) {
    match lines {
        [] => {}
        [only] => {
            let _ = writeln!(out, "{indent}/** {only} */");
        }
        _ => {
            let _ = writeln!(out, "{indent}/**");
            for line in lines {
                if line.is_empty() {
                    let _ = writeln!(out, "{indent} *");
                } else {
                    let _ = writeln!(out, "{indent} * {line}");
                }
            }
            let _ = writeln!(out, "{indent} */");
        }
    }
}

/// A command's field is an argument rather than a property, so its prose belongs
/// to the writer's parameter.
fn param(doc: &mut Vec<String>, name: &str, text: Option<&str>) {
    let Some(text) = text else { return };
    let mut lines = text.lines();
    let Some(first) = lines.next() else { return };
    doc.push(format!("@param {name} - {first}"));
    for line in lines {
        doc.push(format!("  {line}"));
    }
}

/// `frame_offset` belongs to the slot's header, so a command writer takes the
/// header's own prose rather than repeating it per command.
fn slot_field_doc<'a>(schema: &'a Schema, field: &str) -> Option<&'a str> {
    schema
        .records
        .get("command_slot")?
        .fields
        .iter()
        .find(|candidate| candidate.name == field)?
        .doc
        .as_deref()
}

/// The cold-path read of ADR-0018: a snapshot rather than a view, so that a
/// caller holds values instead of an object over live memory. Writes stay the
/// separate `store`/`write` functions.
fn emit_record_reader(out: &mut String, type_name: &str, record_name: &str, record: &Record) {
    let fields: Vec<&Field> = record
        .fields
        .iter()
        .filter(|field| !field.is_array())
        .collect();
    if fields.is_empty() {
        return;
    }

    let plain = fields.iter().any(|field| !field.atomic);
    let atomic = fields.iter().any(|field| field.atomic);
    let mut params: Vec<&str> = Vec::new();
    if plain {
        params.push("view: DataView");
    }
    if atomic {
        params.push("atoms: Int32Array");
    }
    params.push("base: number");

    let mut doc = prose_then(
        record.doc.as_deref(),
        format!("Every field of `{record_name}` at once. Cold path: allocates one object."),
    );
    if plain {
        param(&mut doc, "view", Some(&view_over(record_name)));
    }
    if atomic {
        param(&mut doc, "atoms", Some(&shared_array(record_name)));
    }
    param(
        &mut doc,
        "base",
        Some(if atomic { ALIGNED_BASE } else { BASE }),
    );
    emit_block(out, "", &doc);
    let _ = writeln!(
        out,
        "export function read{type_name}({}) {{\n  return {{",
        params.join(", ")
    );
    for field in fields {
        let source = if field.atomic { "atoms" } else { "view" };
        let verb = if field.atomic { "load" } else { "read" };
        let _ = writeln!(
            out,
            "    {}: {verb}{type_name}{}({source}, base),",
            camel(&field.name),
            pascal(&field.name)
        );
    }
    let _ = writeln!(out, "  }}\n}}\n");
}

/// A record's array field is a region a caller takes its own view over. The
/// offset alone left the length to be written by hand on the TypeScript side,
/// and a length written by hand is the number the schema exists to remove.
fn emit_record_array(out: &mut String, record_name: &str, field: &Field) {
    let length = format!(
        "{}_{}_LENGTH",
        screaming(record_name),
        screaming(&field.name)
    );
    let array = field.ty.ts_array();

    let _ = writeln!(
        out,
        "/** How many elements `{}` of `{record_name}` holds. */\n\
         export const {length} = {}\n",
        field.name, field.count
    );

    let mut doc = prose_then(
        field.doc.as_deref(),
        format!(
            "A `{array}` over `{}` of `{record_name}`. Cold path: the view is an \
         allocation, so take it once and keep it.",
            field.name
        ),
    );
    param(
        &mut doc,
        "buffer",
        Some(&format!("The memory `{record_name}` lives in.")),
    );
    // A single byte has no alignment to demand.
    param(
        &mut doc,
        "base",
        Some(&if field.ty.size() > 1 {
            format!(
                "Byte offset of the record, itself a multiple of {}.",
                field.ty.size()
            )
        } else {
            BASE.to_owned()
        }),
    );
    emit_block(out, "", &doc);
    let _ = writeln!(
        out,
        "export function {}(buffer: ArrayBufferLike, base: number): {array} {{\n  \
         return new {array}({}, {length})\n}}\n",
        camel(&format!("{record_name}_{}", field.name)),
        offset_expr("buffer, base", field.offset, None),
    );
}

/// The writer fills every byte the field reserved: an element the caller left
/// out is written as zero.
fn emit_array_field(out: &mut String, type_name: &str, command: &str, field: &Field) {
    let field_name = pascal(&field.name);
    let value = camel(&field.name);
    let array = field.ty.ts_array();
    let count = field.count;
    let at = offset_expr(PAYLOAD_BASE, field.offset, Some(field.ty.size()));

    let mut doc = prose_then(
        field.doc.as_deref(),
        format!(
            "Copies `{}` into a `{command}` slot, zero-filling anything the caller \
         left short. Hot path: no allocation.",
            field.name
        ),
    );
    param(&mut doc, "view", Some(RING_VIEW));
    param(&mut doc, "slot", Some(SLOT_WRITE));
    param(&mut doc, &value, field.doc.as_deref());
    emit_block(out, "", &doc);
    let _ = writeln!(
        out,
        "export function write{type_name}{field_name}(view: DataView, slot: number, {value}: {array}): void {{\n  \
         for (let i = 0; i < {count}; i++) {{\n    {}\n  }}\n}}\n",
        view_set(field.ty, &at, &format!("{value}[i] ?? 0"))
    );
    let mut doc = prose_then(
        field.doc.as_deref(),
        format!(
            "Reads `{}` back out of a `{command}` slot. Cold path: allocates the array.",
            field.name
        ),
    );
    param(&mut doc, "view", Some(RING_VIEW));
    param(&mut doc, "slot", Some(SLOT_READ));
    emit_block(out, "", &doc);
    let _ = writeln!(
        out,
        "export function read{type_name}{field_name}(view: DataView, slot: number): {array} {{\n  \
         const out = new {array}({count})\n  \
         for (let i = 0; i < {count}; i++) {{\n    out[i] = {}\n  }}\n  \
         return out\n}}\n",
        view_get(field.ty, &at)
    );
}
